// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fci_core_fci_core,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.600000,HLS_SYN_LAT=3200,HLS_SYN_TPT=3197,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=11169,HLS_SYN_LUT=9520,HLS_VERSION=2022_2}" *)

module fci_core (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axis_data_TDATA,
        s_axis_data_TKEEP,
        s_axis_data_TSTRB,
        s_axis_data_TUSER,
        s_axis_data_TLAST,
        s_axis_data_TID,
        s_axis_data_TDEST,
        m_axis_result_TDATA,
        m_axis_result_TKEEP,
        m_axis_result_TSTRB,
        m_axis_result_TUSER,
        m_axis_result_TLAST,
        m_axis_result_TID,
        m_axis_result_TDEST,
        s_axis_data_TVALID,
        s_axis_data_TREADY,
        m_axis_result_TVALID,
        m_axis_result_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [15:0] s_axis_data_TDATA;
input  [1:0] s_axis_data_TKEEP;
input  [1:0] s_axis_data_TSTRB;
input  [63:0] s_axis_data_TUSER;
input  [0:0] s_axis_data_TLAST;
input  [0:0] s_axis_data_TID;
input  [0:0] s_axis_data_TDEST;
output  [31:0] m_axis_result_TDATA;
output  [3:0] m_axis_result_TKEEP;
output  [3:0] m_axis_result_TSTRB;
output  [63:0] m_axis_result_TUSER;
output  [0:0] m_axis_result_TLAST;
output  [0:0] m_axis_result_TID;
output  [0:0] m_axis_result_TDEST;
input   s_axis_data_TVALID;
output   s_axis_data_TREADY;
output   m_axis_result_TVALID;
input   m_axis_result_TREADY;

 reg    ap_rst_n_inv;
wire   [9:0] psa_l_lo;
wire   [9:0] psa_l_hi;
wire   [9:0] psa_w_lo;
wire   [9:0] psa_w_hi;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [9:0] entry_proc_U0_psa_l_lo_c_din;
wire    entry_proc_U0_psa_l_lo_c_write;
wire   [9:0] entry_proc_U0_psa_l_hi_c_din;
wire    entry_proc_U0_psa_l_hi_c_write;
wire   [9:0] entry_proc_U0_psa_w_lo_c_din;
wire    entry_proc_U0_psa_w_lo_c_write;
wire   [9:0] entry_proc_U0_psa_w_hi_c_din;
wire    entry_proc_U0_psa_w_hi_c_write;
wire    axis_to_fft_U0_ap_start;
wire    axis_to_fft_U0_ap_done;
wire    axis_to_fft_U0_ap_continue;
wire    axis_to_fft_U0_ap_idle;
wire    axis_to_fft_U0_ap_ready;
wire    axis_to_fft_U0_start_out;
wire    axis_to_fft_U0_start_write;
wire    axis_to_fft_U0_s_axis_data_TREADY;
wire   [31:0] axis_to_fft_U0_xn_s_din;
wire    axis_to_fft_U0_xn_s_write;
wire   [7:0] axis_to_fft_U0_config_s18_din;
wire    axis_to_fft_U0_config_s18_write;
wire   [63:0] axis_to_fft_U0_tag_s19_din;
wire    axis_to_fft_U0_tag_s19_write;
wire    fft_fci_fft_config_U0_ap_start;
wire    fft_fci_fft_config_U0_ap_done;
wire    fft_fci_fft_config_U0_ap_continue;
wire    fft_fci_fft_config_U0_ap_idle;
wire    fft_fci_fft_config_U0_ap_ready;
wire    fft_fci_fft_config_U0_xn_s_read;
wire   [31:0] fft_fci_fft_config_U0_xk_s_din;
wire    fft_fci_fft_config_U0_xk_s_write;
wire   [7:0] fft_fci_fft_config_U0_status_s17_din;
wire    fft_fci_fft_config_U0_status_s17_write;
wire    fft_fci_fft_config_U0_config_s18_read;
wire    fft_to_psa_U0_ap_start;
wire    fft_to_psa_U0_ap_done;
wire    fft_to_psa_U0_ap_continue;
wire    fft_to_psa_U0_ap_idle;
wire    fft_to_psa_U0_ap_ready;
wire    fft_to_psa_U0_xk_s_read;
wire    fft_to_psa_U0_status_s17_read;
wire    fft_to_psa_U0_psa_l_lo_read;
wire    fft_to_psa_U0_psa_l_hi_read;
wire    fft_to_psa_U0_psa_w_lo_read;
wire    fft_to_psa_U0_psa_w_hi_read;
wire   [31:0] fft_to_psa_U0_m_axis_result_TDATA;
wire    fft_to_psa_U0_m_axis_result_TVALID;
wire   [3:0] fft_to_psa_U0_m_axis_result_TKEEP;
wire   [3:0] fft_to_psa_U0_m_axis_result_TSTRB;
wire   [63:0] fft_to_psa_U0_m_axis_result_TUSER;
wire   [0:0] fft_to_psa_U0_m_axis_result_TLAST;
wire   [0:0] fft_to_psa_U0_m_axis_result_TID;
wire   [0:0] fft_to_psa_U0_m_axis_result_TDEST;
wire    fft_to_psa_U0_tag_s19_read;
wire    psa_l_lo_c_full_n;
wire   [9:0] psa_l_lo_c_dout;
wire   [2:0] psa_l_lo_c_num_data_valid;
wire   [2:0] psa_l_lo_c_fifo_cap;
wire    psa_l_lo_c_empty_n;
wire    psa_l_hi_c_full_n;
wire   [9:0] psa_l_hi_c_dout;
wire   [2:0] psa_l_hi_c_num_data_valid;
wire   [2:0] psa_l_hi_c_fifo_cap;
wire    psa_l_hi_c_empty_n;
wire    psa_w_lo_c_full_n;
wire   [9:0] psa_w_lo_c_dout;
wire   [2:0] psa_w_lo_c_num_data_valid;
wire   [2:0] psa_w_lo_c_fifo_cap;
wire    psa_w_lo_c_empty_n;
wire    psa_w_hi_c_full_n;
wire   [9:0] psa_w_hi_c_dout;
wire   [2:0] psa_w_hi_c_num_data_valid;
wire   [2:0] psa_w_hi_c_fifo_cap;
wire    psa_w_hi_c_empty_n;
wire    xn_s_full_n;
wire   [31:0] xn_s_dout;
wire   [1:0] xn_s_num_data_valid;
wire   [1:0] xn_s_fifo_cap;
wire    xn_s_empty_n;
wire    config_s_full_n;
wire   [7:0] config_s_dout;
wire   [1:0] config_s_num_data_valid;
wire   [1:0] config_s_fifo_cap;
wire    config_s_empty_n;
wire    tag_s_full_n;
wire   [63:0] tag_s_dout;
wire   [1:0] tag_s_num_data_valid;
wire   [1:0] tag_s_fifo_cap;
wire    tag_s_empty_n;
wire    xk_s_full_n;
wire   [31:0] xk_s_dout;
wire   [1:0] xk_s_num_data_valid;
wire   [1:0] xk_s_fifo_cap;
wire    xk_s_empty_n;
wire    status_s_full_n;
wire   [7:0] status_s_dout;
wire   [1:0] status_s_num_data_valid;
wire   [1:0] status_s_fifo_cap;
wire    status_s_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_axis_to_fft_U0_ap_ready;
wire    ap_sync_axis_to_fft_U0_ap_ready;
wire   [0:0] start_for_fft_to_psa_U0_din;
wire    start_for_fft_to_psa_U0_full_n;
wire   [0:0] start_for_fft_to_psa_U0_dout;
wire    start_for_fft_to_psa_U0_empty_n;
wire   [0:0] start_for_fft_fci_fft_config_U0_din;
wire    start_for_fft_fci_fft_config_U0_full_n;
wire   [0:0] start_for_fft_fci_fft_config_U0_dout;
wire    start_for_fft_fci_fft_config_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_axis_to_fft_U0_ap_ready = 1'b0;
end

fci_core_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .psa_l_lo(psa_l_lo),
    .psa_l_hi(psa_l_hi),
    .psa_w_lo(psa_w_lo),
    .psa_w_hi(psa_w_hi),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

fci_core_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_fft_to_psa_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .psa_l_lo(psa_l_lo),
    .psa_l_lo_c_din(entry_proc_U0_psa_l_lo_c_din),
    .psa_l_lo_c_num_data_valid(psa_l_lo_c_num_data_valid),
    .psa_l_lo_c_fifo_cap(psa_l_lo_c_fifo_cap),
    .psa_l_lo_c_full_n(psa_l_lo_c_full_n),
    .psa_l_lo_c_write(entry_proc_U0_psa_l_lo_c_write),
    .psa_l_hi(psa_l_hi),
    .psa_l_hi_c_din(entry_proc_U0_psa_l_hi_c_din),
    .psa_l_hi_c_num_data_valid(psa_l_hi_c_num_data_valid),
    .psa_l_hi_c_fifo_cap(psa_l_hi_c_fifo_cap),
    .psa_l_hi_c_full_n(psa_l_hi_c_full_n),
    .psa_l_hi_c_write(entry_proc_U0_psa_l_hi_c_write),
    .psa_w_lo(psa_w_lo),
    .psa_w_lo_c_din(entry_proc_U0_psa_w_lo_c_din),
    .psa_w_lo_c_num_data_valid(psa_w_lo_c_num_data_valid),
    .psa_w_lo_c_fifo_cap(psa_w_lo_c_fifo_cap),
    .psa_w_lo_c_full_n(psa_w_lo_c_full_n),
    .psa_w_lo_c_write(entry_proc_U0_psa_w_lo_c_write),
    .psa_w_hi(psa_w_hi),
    .psa_w_hi_c_din(entry_proc_U0_psa_w_hi_c_din),
    .psa_w_hi_c_num_data_valid(psa_w_hi_c_num_data_valid),
    .psa_w_hi_c_fifo_cap(psa_w_hi_c_fifo_cap),
    .psa_w_hi_c_full_n(psa_w_hi_c_full_n),
    .psa_w_hi_c_write(entry_proc_U0_psa_w_hi_c_write)
);

fci_core_axis_to_fft axis_to_fft_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(axis_to_fft_U0_ap_start),
    .start_full_n(start_for_fft_fci_fft_config_U0_full_n),
    .ap_done(axis_to_fft_U0_ap_done),
    .ap_continue(axis_to_fft_U0_ap_continue),
    .ap_idle(axis_to_fft_U0_ap_idle),
    .ap_ready(axis_to_fft_U0_ap_ready),
    .start_out(axis_to_fft_U0_start_out),
    .start_write(axis_to_fft_U0_start_write),
    .s_axis_data_TDATA(s_axis_data_TDATA),
    .s_axis_data_TVALID(s_axis_data_TVALID),
    .s_axis_data_TREADY(axis_to_fft_U0_s_axis_data_TREADY),
    .s_axis_data_TKEEP(s_axis_data_TKEEP),
    .s_axis_data_TSTRB(s_axis_data_TSTRB),
    .s_axis_data_TUSER(s_axis_data_TUSER),
    .s_axis_data_TLAST(s_axis_data_TLAST),
    .s_axis_data_TID(s_axis_data_TID),
    .s_axis_data_TDEST(s_axis_data_TDEST),
    .xn_s_din(axis_to_fft_U0_xn_s_din),
    .xn_s_num_data_valid(xn_s_num_data_valid),
    .xn_s_fifo_cap(xn_s_fifo_cap),
    .xn_s_full_n(xn_s_full_n),
    .xn_s_write(axis_to_fft_U0_xn_s_write),
    .config_s18_din(axis_to_fft_U0_config_s18_din),
    .config_s18_num_data_valid(config_s_num_data_valid),
    .config_s18_fifo_cap(config_s_fifo_cap),
    .config_s18_full_n(config_s_full_n),
    .config_s18_write(axis_to_fft_U0_config_s18_write),
    .tag_s19_din(axis_to_fft_U0_tag_s19_din),
    .tag_s19_num_data_valid(tag_s_num_data_valid),
    .tag_s19_fifo_cap(tag_s_fifo_cap),
    .tag_s19_full_n(tag_s_full_n),
    .tag_s19_write(axis_to_fft_U0_tag_s19_write)
);

fci_core_fft_fci_fft_config_s fft_fci_fft_config_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fft_fci_fft_config_U0_ap_start),
    .ap_done(fft_fci_fft_config_U0_ap_done),
    .ap_continue(fft_fci_fft_config_U0_ap_continue),
    .ap_idle(fft_fci_fft_config_U0_ap_idle),
    .ap_ready(fft_fci_fft_config_U0_ap_ready),
    .xn_s_dout(xn_s_dout),
    .xn_s_num_data_valid(xn_s_num_data_valid),
    .xn_s_fifo_cap(xn_s_fifo_cap),
    .xn_s_empty_n(xn_s_empty_n),
    .xn_s_read(fft_fci_fft_config_U0_xn_s_read),
    .xk_s_din(fft_fci_fft_config_U0_xk_s_din),
    .xk_s_num_data_valid(xk_s_num_data_valid),
    .xk_s_fifo_cap(xk_s_fifo_cap),
    .xk_s_full_n(xk_s_full_n),
    .xk_s_write(fft_fci_fft_config_U0_xk_s_write),
    .status_s17_din(fft_fci_fft_config_U0_status_s17_din),
    .status_s17_num_data_valid(status_s_num_data_valid),
    .status_s17_fifo_cap(status_s_fifo_cap),
    .status_s17_full_n(status_s_full_n),
    .status_s17_write(fft_fci_fft_config_U0_status_s17_write),
    .config_s18_dout(config_s_dout),
    .config_s18_num_data_valid(config_s_num_data_valid),
    .config_s18_fifo_cap(config_s_fifo_cap),
    .config_s18_empty_n(config_s_empty_n),
    .config_s18_read(fft_fci_fft_config_U0_config_s18_read)
);

fci_core_fft_to_psa fft_to_psa_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fft_to_psa_U0_ap_start),
    .ap_done(fft_to_psa_U0_ap_done),
    .ap_continue(fft_to_psa_U0_ap_continue),
    .ap_idle(fft_to_psa_U0_ap_idle),
    .ap_ready(fft_to_psa_U0_ap_ready),
    .xk_s_dout(xk_s_dout),
    .xk_s_num_data_valid(xk_s_num_data_valid),
    .xk_s_fifo_cap(xk_s_fifo_cap),
    .xk_s_empty_n(xk_s_empty_n),
    .xk_s_read(fft_to_psa_U0_xk_s_read),
    .status_s17_dout(status_s_dout),
    .status_s17_num_data_valid(status_s_num_data_valid),
    .status_s17_fifo_cap(status_s_fifo_cap),
    .status_s17_empty_n(status_s_empty_n),
    .status_s17_read(fft_to_psa_U0_status_s17_read),
    .psa_l_lo_dout(psa_l_lo_c_dout),
    .psa_l_lo_num_data_valid(psa_l_lo_c_num_data_valid),
    .psa_l_lo_fifo_cap(psa_l_lo_c_fifo_cap),
    .psa_l_lo_empty_n(psa_l_lo_c_empty_n),
    .psa_l_lo_read(fft_to_psa_U0_psa_l_lo_read),
    .psa_l_hi_dout(psa_l_hi_c_dout),
    .psa_l_hi_num_data_valid(psa_l_hi_c_num_data_valid),
    .psa_l_hi_fifo_cap(psa_l_hi_c_fifo_cap),
    .psa_l_hi_empty_n(psa_l_hi_c_empty_n),
    .psa_l_hi_read(fft_to_psa_U0_psa_l_hi_read),
    .psa_w_lo_dout(psa_w_lo_c_dout),
    .psa_w_lo_num_data_valid(psa_w_lo_c_num_data_valid),
    .psa_w_lo_fifo_cap(psa_w_lo_c_fifo_cap),
    .psa_w_lo_empty_n(psa_w_lo_c_empty_n),
    .psa_w_lo_read(fft_to_psa_U0_psa_w_lo_read),
    .psa_w_hi_dout(psa_w_hi_c_dout),
    .psa_w_hi_num_data_valid(psa_w_hi_c_num_data_valid),
    .psa_w_hi_fifo_cap(psa_w_hi_c_fifo_cap),
    .psa_w_hi_empty_n(psa_w_hi_c_empty_n),
    .psa_w_hi_read(fft_to_psa_U0_psa_w_hi_read),
    .m_axis_result_TDATA(fft_to_psa_U0_m_axis_result_TDATA),
    .m_axis_result_TVALID(fft_to_psa_U0_m_axis_result_TVALID),
    .m_axis_result_TREADY(m_axis_result_TREADY),
    .m_axis_result_TKEEP(fft_to_psa_U0_m_axis_result_TKEEP),
    .m_axis_result_TSTRB(fft_to_psa_U0_m_axis_result_TSTRB),
    .m_axis_result_TUSER(fft_to_psa_U0_m_axis_result_TUSER),
    .m_axis_result_TLAST(fft_to_psa_U0_m_axis_result_TLAST),
    .m_axis_result_TID(fft_to_psa_U0_m_axis_result_TID),
    .m_axis_result_TDEST(fft_to_psa_U0_m_axis_result_TDEST),
    .tag_s19_dout(tag_s_dout),
    .tag_s19_num_data_valid(tag_s_num_data_valid),
    .tag_s19_fifo_cap(tag_s_fifo_cap),
    .tag_s19_empty_n(tag_s_empty_n),
    .tag_s19_read(fft_to_psa_U0_tag_s19_read)
);

fci_core_fifo_w10_d4_S psa_l_lo_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_psa_l_lo_c_din),
    .if_full_n(psa_l_lo_c_full_n),
    .if_write(entry_proc_U0_psa_l_lo_c_write),
    .if_dout(psa_l_lo_c_dout),
    .if_num_data_valid(psa_l_lo_c_num_data_valid),
    .if_fifo_cap(psa_l_lo_c_fifo_cap),
    .if_empty_n(psa_l_lo_c_empty_n),
    .if_read(fft_to_psa_U0_psa_l_lo_read)
);

fci_core_fifo_w10_d4_S psa_l_hi_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_psa_l_hi_c_din),
    .if_full_n(psa_l_hi_c_full_n),
    .if_write(entry_proc_U0_psa_l_hi_c_write),
    .if_dout(psa_l_hi_c_dout),
    .if_num_data_valid(psa_l_hi_c_num_data_valid),
    .if_fifo_cap(psa_l_hi_c_fifo_cap),
    .if_empty_n(psa_l_hi_c_empty_n),
    .if_read(fft_to_psa_U0_psa_l_hi_read)
);

fci_core_fifo_w10_d4_S psa_w_lo_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_psa_w_lo_c_din),
    .if_full_n(psa_w_lo_c_full_n),
    .if_write(entry_proc_U0_psa_w_lo_c_write),
    .if_dout(psa_w_lo_c_dout),
    .if_num_data_valid(psa_w_lo_c_num_data_valid),
    .if_fifo_cap(psa_w_lo_c_fifo_cap),
    .if_empty_n(psa_w_lo_c_empty_n),
    .if_read(fft_to_psa_U0_psa_w_lo_read)
);

fci_core_fifo_w10_d4_S psa_w_hi_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_psa_w_hi_c_din),
    .if_full_n(psa_w_hi_c_full_n),
    .if_write(entry_proc_U0_psa_w_hi_c_write),
    .if_dout(psa_w_hi_c_dout),
    .if_num_data_valid(psa_w_hi_c_num_data_valid),
    .if_fifo_cap(psa_w_hi_c_fifo_cap),
    .if_empty_n(psa_w_hi_c_empty_n),
    .if_read(fft_to_psa_U0_psa_w_hi_read)
);

fci_core_fifo_w32_d2_S xn_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_fft_U0_xn_s_din),
    .if_full_n(xn_s_full_n),
    .if_write(axis_to_fft_U0_xn_s_write),
    .if_dout(xn_s_dout),
    .if_num_data_valid(xn_s_num_data_valid),
    .if_fifo_cap(xn_s_fifo_cap),
    .if_empty_n(xn_s_empty_n),
    .if_read(fft_fci_fft_config_U0_xn_s_read)
);

fci_core_fifo_w8_d2_S config_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_fft_U0_config_s18_din),
    .if_full_n(config_s_full_n),
    .if_write(axis_to_fft_U0_config_s18_write),
    .if_dout(config_s_dout),
    .if_num_data_valid(config_s_num_data_valid),
    .if_fifo_cap(config_s_fifo_cap),
    .if_empty_n(config_s_empty_n),
    .if_read(fft_fci_fft_config_U0_config_s18_read)
);

fci_core_fifo_w64_d2_S tag_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_fft_U0_tag_s19_din),
    .if_full_n(tag_s_full_n),
    .if_write(axis_to_fft_U0_tag_s19_write),
    .if_dout(tag_s_dout),
    .if_num_data_valid(tag_s_num_data_valid),
    .if_fifo_cap(tag_s_fifo_cap),
    .if_empty_n(tag_s_empty_n),
    .if_read(fft_to_psa_U0_tag_s19_read)
);

fci_core_fifo_w32_d2_S xk_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_fci_fft_config_U0_xk_s_din),
    .if_full_n(xk_s_full_n),
    .if_write(fft_fci_fft_config_U0_xk_s_write),
    .if_dout(xk_s_dout),
    .if_num_data_valid(xk_s_num_data_valid),
    .if_fifo_cap(xk_s_fifo_cap),
    .if_empty_n(xk_s_empty_n),
    .if_read(fft_to_psa_U0_xk_s_read)
);

fci_core_fifo_w8_d2_S status_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_fci_fft_config_U0_status_s17_din),
    .if_full_n(status_s_full_n),
    .if_write(fft_fci_fft_config_U0_status_s17_write),
    .if_dout(status_s_dout),
    .if_num_data_valid(status_s_num_data_valid),
    .if_fifo_cap(status_s_fifo_cap),
    .if_empty_n(status_s_empty_n),
    .if_read(fft_to_psa_U0_status_s17_read)
);

fci_core_start_for_fft_to_psa_U0 start_for_fft_to_psa_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_to_psa_U0_din),
    .if_full_n(start_for_fft_to_psa_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_fft_to_psa_U0_dout),
    .if_empty_n(start_for_fft_to_psa_U0_empty_n),
    .if_read(fft_to_psa_U0_ap_ready)
);

fci_core_start_for_fft_fci_fft_config_U0 start_for_fft_fci_fft_config_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_fci_fft_config_U0_din),
    .if_full_n(start_for_fft_fci_fft_config_U0_full_n),
    .if_write(axis_to_fft_U0_start_write),
    .if_dout(start_for_fft_fci_fft_config_U0_dout),
    .if_empty_n(start_for_fft_fci_fft_config_U0_empty_n),
    .if_read(fft_fci_fft_config_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_axis_to_fft_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_axis_to_fft_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_axis_to_fft_U0_ap_ready <= ap_sync_axis_to_fft_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign ap_done = fft_to_psa_U0_ap_done;

assign ap_idle = (fft_to_psa_U0_ap_idle & fft_fci_fft_config_U0_ap_idle & entry_proc_U0_ap_idle & axis_to_fft_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_axis_to_fft_U0_ap_ready = (axis_to_fft_U0_ap_ready | ap_sync_reg_axis_to_fft_U0_ap_ready);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_axis_to_fft_U0_ap_ready);

assign axis_to_fft_U0_ap_continue = 1'b1;

assign axis_to_fft_U0_ap_start = ((ap_sync_reg_axis_to_fft_U0_ap_ready ^ 1'b1) & ap_start);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign fft_fci_fft_config_U0_ap_continue = 1'b1;

assign fft_fci_fft_config_U0_ap_start = start_for_fft_fci_fft_config_U0_empty_n;

assign fft_to_psa_U0_ap_continue = 1'b1;

assign fft_to_psa_U0_ap_start = start_for_fft_to_psa_U0_empty_n;

assign m_axis_result_TDATA = fft_to_psa_U0_m_axis_result_TDATA;

assign m_axis_result_TDEST = fft_to_psa_U0_m_axis_result_TDEST;

assign m_axis_result_TID = fft_to_psa_U0_m_axis_result_TID;

assign m_axis_result_TKEEP = fft_to_psa_U0_m_axis_result_TKEEP;

assign m_axis_result_TLAST = fft_to_psa_U0_m_axis_result_TLAST;

assign m_axis_result_TSTRB = fft_to_psa_U0_m_axis_result_TSTRB;

assign m_axis_result_TUSER = fft_to_psa_U0_m_axis_result_TUSER;

assign m_axis_result_TVALID = fft_to_psa_U0_m_axis_result_TVALID;

assign s_axis_data_TREADY = axis_to_fft_U0_s_axis_data_TREADY;

assign start_for_fft_fci_fft_config_U0_din = 1'b1;

assign start_for_fft_to_psa_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "fci_core_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "fci_core_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fci_core

