// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fci_core_fci_core,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.600000,HLS_SYN_LAT=3200,HLS_SYN_TPT=3197,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=10440,HLS_SYN_LUT=8862,HLS_VERSION=2022_2}" *)

module fci_core (
        s_axis_data_TDATA,
        s_axis_data_TKEEP,
        s_axis_data_TSTRB,
        s_axis_data_TUSER,
        s_axis_data_TLAST,
        s_axis_data_TID,
        s_axis_data_TDEST,
        m_axis_result_TDATA,
        m_axis_result_TKEEP,
        m_axis_result_TSTRB,
        m_axis_result_TUSER,
        m_axis_result_TLAST,
        m_axis_result_TID,
        m_axis_result_TDEST,
        psa_l_lo_s_dout,
        psa_l_lo_s_empty_n,
        psa_l_lo_s_read,
        psa_l_hi_s_dout,
        psa_l_hi_s_empty_n,
        psa_l_hi_s_read,
        psa_w_lo_s_dout,
        psa_w_lo_s_empty_n,
        psa_w_lo_s_read,
        psa_w_hi_s_dout,
        psa_w_hi_s_empty_n,
        psa_w_hi_s_read,
        ap_clk,
        ap_rst_n,
        s_axis_data_TVALID,
        s_axis_data_TREADY,
        m_axis_result_TVALID,
        m_axis_result_TREADY
);


input  [15:0] s_axis_data_TDATA;
input  [1:0] s_axis_data_TKEEP;
input  [1:0] s_axis_data_TSTRB;
input  [0:0] s_axis_data_TUSER;
input  [0:0] s_axis_data_TLAST;
input  [0:0] s_axis_data_TID;
input  [0:0] s_axis_data_TDEST;
output  [31:0] m_axis_result_TDATA;
output  [3:0] m_axis_result_TKEEP;
output  [3:0] m_axis_result_TSTRB;
output  [0:0] m_axis_result_TUSER;
output  [0:0] m_axis_result_TLAST;
output  [0:0] m_axis_result_TID;
output  [0:0] m_axis_result_TDEST;
input  [9:0] psa_l_lo_s_dout;
input   psa_l_lo_s_empty_n;
output   psa_l_lo_s_read;
input  [9:0] psa_l_hi_s_dout;
input   psa_l_hi_s_empty_n;
output   psa_l_hi_s_read;
input  [9:0] psa_w_lo_s_dout;
input   psa_w_lo_s_empty_n;
output   psa_w_lo_s_read;
input  [9:0] psa_w_hi_s_dout;
input   psa_w_hi_s_empty_n;
output   psa_w_hi_s_read;
input   ap_clk;
input   ap_rst_n;
input   s_axis_data_TVALID;
output   s_axis_data_TREADY;
output   m_axis_result_TVALID;
input   m_axis_result_TREADY;

 reg    ap_rst_n_inv;
wire    axis_to_fft_U0_ap_start;
wire    axis_to_fft_U0_ap_done;
wire    axis_to_fft_U0_ap_continue;
wire    axis_to_fft_U0_ap_idle;
wire    axis_to_fft_U0_ap_ready;
wire    axis_to_fft_U0_start_out;
wire    axis_to_fft_U0_start_write;
wire    axis_to_fft_U0_s_axis_data_TREADY;
wire   [31:0] axis_to_fft_U0_xn_s_din;
wire    axis_to_fft_U0_xn_s_write;
wire   [7:0] axis_to_fft_U0_config_s5_din;
wire    axis_to_fft_U0_config_s5_write;
wire    fft_fci_fft_config_U0_ap_start;
wire    fft_fci_fft_config_U0_ap_done;
wire    fft_fci_fft_config_U0_ap_continue;
wire    fft_fci_fft_config_U0_ap_idle;
wire    fft_fci_fft_config_U0_ap_ready;
wire    fft_fci_fft_config_U0_start_out;
wire    fft_fci_fft_config_U0_start_write;
wire    fft_fci_fft_config_U0_xn_s_read;
wire   [31:0] fft_fci_fft_config_U0_xk_s_din;
wire    fft_fci_fft_config_U0_xk_s_write;
wire   [7:0] fft_fci_fft_config_U0_status_s4_din;
wire    fft_fci_fft_config_U0_status_s4_write;
wire    fft_fci_fft_config_U0_config_s5_read;
wire    fft_to_psa_U0_ap_start;
wire    fft_to_psa_U0_ap_done;
wire    fft_to_psa_U0_ap_continue;
wire    fft_to_psa_U0_ap_idle;
wire    fft_to_psa_U0_ap_ready;
wire    fft_to_psa_U0_xk_s_read;
wire    fft_to_psa_U0_status_s4_read;
wire    fft_to_psa_U0_psa_l_lo_s_read;
wire    fft_to_psa_U0_psa_l_hi_s_read;
wire    fft_to_psa_U0_psa_w_lo_s_read;
wire    fft_to_psa_U0_psa_w_hi_s_read;
wire   [31:0] fft_to_psa_U0_m_axis_result_TDATA;
wire    fft_to_psa_U0_m_axis_result_TVALID;
wire   [3:0] fft_to_psa_U0_m_axis_result_TKEEP;
wire   [3:0] fft_to_psa_U0_m_axis_result_TSTRB;
wire   [0:0] fft_to_psa_U0_m_axis_result_TUSER;
wire   [0:0] fft_to_psa_U0_m_axis_result_TLAST;
wire   [0:0] fft_to_psa_U0_m_axis_result_TID;
wire   [0:0] fft_to_psa_U0_m_axis_result_TDEST;
wire    xn_s_full_n;
wire   [31:0] xn_s_dout;
wire   [1:0] xn_s_num_data_valid;
wire   [1:0] xn_s_fifo_cap;
wire    xn_s_empty_n;
wire    config_s_full_n;
wire   [7:0] config_s_dout;
wire   [1:0] config_s_num_data_valid;
wire   [1:0] config_s_fifo_cap;
wire    config_s_empty_n;
wire    xk_s_full_n;
wire   [31:0] xk_s_dout;
wire   [1:0] xk_s_num_data_valid;
wire   [1:0] xk_s_fifo_cap;
wire    xk_s_empty_n;
wire    status_s_full_n;
wire   [7:0] status_s_dout;
wire   [1:0] status_s_num_data_valid;
wire   [1:0] status_s_fifo_cap;
wire    status_s_empty_n;
wire   [0:0] start_for_fft_fci_fft_config_U0_din;
wire    start_for_fft_fci_fft_config_U0_full_n;
wire   [0:0] start_for_fft_fci_fft_config_U0_dout;
wire    start_for_fft_fci_fft_config_U0_empty_n;
wire   [0:0] start_for_fft_to_psa_U0_din;
wire    start_for_fft_to_psa_U0_full_n;
wire   [0:0] start_for_fft_to_psa_U0_dout;
wire    start_for_fft_to_psa_U0_empty_n;

fci_core_axis_to_fft axis_to_fft_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(axis_to_fft_U0_ap_start),
    .start_full_n(start_for_fft_fci_fft_config_U0_full_n),
    .ap_done(axis_to_fft_U0_ap_done),
    .ap_continue(axis_to_fft_U0_ap_continue),
    .ap_idle(axis_to_fft_U0_ap_idle),
    .ap_ready(axis_to_fft_U0_ap_ready),
    .start_out(axis_to_fft_U0_start_out),
    .start_write(axis_to_fft_U0_start_write),
    .s_axis_data_TDATA(s_axis_data_TDATA),
    .s_axis_data_TVALID(s_axis_data_TVALID),
    .s_axis_data_TREADY(axis_to_fft_U0_s_axis_data_TREADY),
    .s_axis_data_TKEEP(s_axis_data_TKEEP),
    .s_axis_data_TSTRB(s_axis_data_TSTRB),
    .s_axis_data_TUSER(s_axis_data_TUSER),
    .s_axis_data_TLAST(s_axis_data_TLAST),
    .s_axis_data_TID(s_axis_data_TID),
    .s_axis_data_TDEST(s_axis_data_TDEST),
    .xn_s_din(axis_to_fft_U0_xn_s_din),
    .xn_s_num_data_valid(xn_s_num_data_valid),
    .xn_s_fifo_cap(xn_s_fifo_cap),
    .xn_s_full_n(xn_s_full_n),
    .xn_s_write(axis_to_fft_U0_xn_s_write),
    .config_s5_din(axis_to_fft_U0_config_s5_din),
    .config_s5_num_data_valid(config_s_num_data_valid),
    .config_s5_fifo_cap(config_s_fifo_cap),
    .config_s5_full_n(config_s_full_n),
    .config_s5_write(axis_to_fft_U0_config_s5_write)
);

fci_core_fft_fci_fft_config_s fft_fci_fft_config_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fft_fci_fft_config_U0_ap_start),
    .start_full_n(start_for_fft_to_psa_U0_full_n),
    .ap_done(fft_fci_fft_config_U0_ap_done),
    .ap_continue(fft_fci_fft_config_U0_ap_continue),
    .ap_idle(fft_fci_fft_config_U0_ap_idle),
    .ap_ready(fft_fci_fft_config_U0_ap_ready),
    .start_out(fft_fci_fft_config_U0_start_out),
    .start_write(fft_fci_fft_config_U0_start_write),
    .xn_s_dout(xn_s_dout),
    .xn_s_num_data_valid(xn_s_num_data_valid),
    .xn_s_fifo_cap(xn_s_fifo_cap),
    .xn_s_empty_n(xn_s_empty_n),
    .xn_s_read(fft_fci_fft_config_U0_xn_s_read),
    .xk_s_din(fft_fci_fft_config_U0_xk_s_din),
    .xk_s_num_data_valid(xk_s_num_data_valid),
    .xk_s_fifo_cap(xk_s_fifo_cap),
    .xk_s_full_n(xk_s_full_n),
    .xk_s_write(fft_fci_fft_config_U0_xk_s_write),
    .status_s4_din(fft_fci_fft_config_U0_status_s4_din),
    .status_s4_num_data_valid(status_s_num_data_valid),
    .status_s4_fifo_cap(status_s_fifo_cap),
    .status_s4_full_n(status_s_full_n),
    .status_s4_write(fft_fci_fft_config_U0_status_s4_write),
    .config_s5_dout(config_s_dout),
    .config_s5_num_data_valid(config_s_num_data_valid),
    .config_s5_fifo_cap(config_s_fifo_cap),
    .config_s5_empty_n(config_s_empty_n),
    .config_s5_read(fft_fci_fft_config_U0_config_s5_read)
);

fci_core_fft_to_psa fft_to_psa_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fft_to_psa_U0_ap_start),
    .ap_done(fft_to_psa_U0_ap_done),
    .ap_continue(fft_to_psa_U0_ap_continue),
    .ap_idle(fft_to_psa_U0_ap_idle),
    .ap_ready(fft_to_psa_U0_ap_ready),
    .xk_s_dout(xk_s_dout),
    .xk_s_num_data_valid(xk_s_num_data_valid),
    .xk_s_fifo_cap(xk_s_fifo_cap),
    .xk_s_empty_n(xk_s_empty_n),
    .xk_s_read(fft_to_psa_U0_xk_s_read),
    .status_s4_dout(status_s_dout),
    .status_s4_num_data_valid(status_s_num_data_valid),
    .status_s4_fifo_cap(status_s_fifo_cap),
    .status_s4_empty_n(status_s_empty_n),
    .status_s4_read(fft_to_psa_U0_status_s4_read),
    .psa_l_lo_s_dout(psa_l_lo_s_dout),
    .psa_l_lo_s_empty_n(psa_l_lo_s_empty_n),
    .psa_l_lo_s_read(fft_to_psa_U0_psa_l_lo_s_read),
    .psa_l_hi_s_dout(psa_l_hi_s_dout),
    .psa_l_hi_s_empty_n(psa_l_hi_s_empty_n),
    .psa_l_hi_s_read(fft_to_psa_U0_psa_l_hi_s_read),
    .psa_w_lo_s_dout(psa_w_lo_s_dout),
    .psa_w_lo_s_empty_n(psa_w_lo_s_empty_n),
    .psa_w_lo_s_read(fft_to_psa_U0_psa_w_lo_s_read),
    .psa_w_hi_s_dout(psa_w_hi_s_dout),
    .psa_w_hi_s_empty_n(psa_w_hi_s_empty_n),
    .psa_w_hi_s_read(fft_to_psa_U0_psa_w_hi_s_read),
    .m_axis_result_TDATA(fft_to_psa_U0_m_axis_result_TDATA),
    .m_axis_result_TVALID(fft_to_psa_U0_m_axis_result_TVALID),
    .m_axis_result_TREADY(m_axis_result_TREADY),
    .m_axis_result_TKEEP(fft_to_psa_U0_m_axis_result_TKEEP),
    .m_axis_result_TSTRB(fft_to_psa_U0_m_axis_result_TSTRB),
    .m_axis_result_TUSER(fft_to_psa_U0_m_axis_result_TUSER),
    .m_axis_result_TLAST(fft_to_psa_U0_m_axis_result_TLAST),
    .m_axis_result_TID(fft_to_psa_U0_m_axis_result_TID),
    .m_axis_result_TDEST(fft_to_psa_U0_m_axis_result_TDEST)
);

fci_core_fifo_w32_d2_S xn_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_fft_U0_xn_s_din),
    .if_full_n(xn_s_full_n),
    .if_write(axis_to_fft_U0_xn_s_write),
    .if_dout(xn_s_dout),
    .if_num_data_valid(xn_s_num_data_valid),
    .if_fifo_cap(xn_s_fifo_cap),
    .if_empty_n(xn_s_empty_n),
    .if_read(fft_fci_fft_config_U0_xn_s_read)
);

fci_core_fifo_w8_d2_S config_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_fft_U0_config_s5_din),
    .if_full_n(config_s_full_n),
    .if_write(axis_to_fft_U0_config_s5_write),
    .if_dout(config_s_dout),
    .if_num_data_valid(config_s_num_data_valid),
    .if_fifo_cap(config_s_fifo_cap),
    .if_empty_n(config_s_empty_n),
    .if_read(fft_fci_fft_config_U0_config_s5_read)
);

fci_core_fifo_w32_d2_S xk_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_fci_fft_config_U0_xk_s_din),
    .if_full_n(xk_s_full_n),
    .if_write(fft_fci_fft_config_U0_xk_s_write),
    .if_dout(xk_s_dout),
    .if_num_data_valid(xk_s_num_data_valid),
    .if_fifo_cap(xk_s_fifo_cap),
    .if_empty_n(xk_s_empty_n),
    .if_read(fft_to_psa_U0_xk_s_read)
);

fci_core_fifo_w8_d2_S status_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_fci_fft_config_U0_status_s4_din),
    .if_full_n(status_s_full_n),
    .if_write(fft_fci_fft_config_U0_status_s4_write),
    .if_dout(status_s_dout),
    .if_num_data_valid(status_s_num_data_valid),
    .if_fifo_cap(status_s_fifo_cap),
    .if_empty_n(status_s_empty_n),
    .if_read(fft_to_psa_U0_status_s4_read)
);

fci_core_start_for_fft_fci_fft_config_U0 start_for_fft_fci_fft_config_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_fci_fft_config_U0_din),
    .if_full_n(start_for_fft_fci_fft_config_U0_full_n),
    .if_write(axis_to_fft_U0_start_write),
    .if_dout(start_for_fft_fci_fft_config_U0_dout),
    .if_empty_n(start_for_fft_fci_fft_config_U0_empty_n),
    .if_read(fft_fci_fft_config_U0_ap_ready)
);

fci_core_start_for_fft_to_psa_U0 start_for_fft_to_psa_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_to_psa_U0_din),
    .if_full_n(start_for_fft_to_psa_U0_full_n),
    .if_write(fft_fci_fft_config_U0_start_write),
    .if_dout(start_for_fft_to_psa_U0_dout),
    .if_empty_n(start_for_fft_to_psa_U0_empty_n),
    .if_read(fft_to_psa_U0_ap_ready)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign axis_to_fft_U0_ap_continue = 1'b1;

assign axis_to_fft_U0_ap_start = 1'b1;

assign fft_fci_fft_config_U0_ap_continue = 1'b1;

assign fft_fci_fft_config_U0_ap_start = start_for_fft_fci_fft_config_U0_empty_n;

assign fft_to_psa_U0_ap_continue = 1'b1;

assign fft_to_psa_U0_ap_start = start_for_fft_to_psa_U0_empty_n;

assign m_axis_result_TDATA = fft_to_psa_U0_m_axis_result_TDATA;

assign m_axis_result_TDEST = fft_to_psa_U0_m_axis_result_TDEST;

assign m_axis_result_TID = fft_to_psa_U0_m_axis_result_TID;

assign m_axis_result_TKEEP = fft_to_psa_U0_m_axis_result_TKEEP;

assign m_axis_result_TLAST = fft_to_psa_U0_m_axis_result_TLAST;

assign m_axis_result_TSTRB = fft_to_psa_U0_m_axis_result_TSTRB;

assign m_axis_result_TUSER = fft_to_psa_U0_m_axis_result_TUSER;

assign m_axis_result_TVALID = fft_to_psa_U0_m_axis_result_TVALID;

assign psa_l_hi_s_read = fft_to_psa_U0_psa_l_hi_s_read;

assign psa_l_lo_s_read = fft_to_psa_U0_psa_l_lo_s_read;

assign psa_w_hi_s_read = fft_to_psa_U0_psa_w_hi_s_read;

assign psa_w_lo_s_read = fft_to_psa_U0_psa_w_lo_s_read;

assign s_axis_data_TREADY = axis_to_fft_U0_s_axis_data_TREADY;

assign start_for_fft_fci_fft_config_U0_din = 1'b1;

assign start_for_fft_to_psa_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "fci_core_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "fci_core_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fci_core

