// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fci_core_axis_to_fft (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_axis_data_TDATA,
        s_axis_data_TVALID,
        s_axis_data_TREADY,
        s_axis_data_TKEEP,
        s_axis_data_TSTRB,
        s_axis_data_TUSER,
        s_axis_data_TLAST,
        s_axis_data_TID,
        s_axis_data_TDEST,
        xn_s_din,
        xn_s_num_data_valid,
        xn_s_fifo_cap,
        xn_s_full_n,
        xn_s_write,
        config_s5_din,
        config_s5_num_data_valid,
        config_s5_fifo_cap,
        config_s5_full_n,
        config_s5_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] s_axis_data_TDATA;
input   s_axis_data_TVALID;
output   s_axis_data_TREADY;
input  [1:0] s_axis_data_TKEEP;
input  [1:0] s_axis_data_TSTRB;
input  [0:0] s_axis_data_TUSER;
input  [0:0] s_axis_data_TLAST;
input  [0:0] s_axis_data_TID;
input  [0:0] s_axis_data_TDEST;
output  [31:0] xn_s_din;
input  [1:0] xn_s_num_data_valid;
input  [1:0] xn_s_fifo_cap;
input   xn_s_full_n;
output   xn_s_write;
output  [7:0] config_s5_din;
input  [1:0] config_s5_num_data_valid;
input  [1:0] config_s5_fifo_cap;
input   config_s5_full_n;
output   config_s5_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg xn_s_write;
reg config_s5_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    config_s5_blk_n;
wire    grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_start;
wire    grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_done;
wire    grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_idle;
wire    grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_ready;
wire   [31:0] grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_xn_s_din;
wire    grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_xn_s_write;
wire    grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_s_axis_data_TREADY;
reg    grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    regslice_both_s_axis_data_V_data_V_U_apdone_blk;
wire   [15:0] s_axis_data_TDATA_int_regslice;
wire    s_axis_data_TVALID_int_regslice;
reg    s_axis_data_TREADY_int_regslice;
wire    regslice_both_s_axis_data_V_data_V_U_ack_in;
wire    regslice_both_s_axis_data_V_keep_V_U_apdone_blk;
wire   [1:0] s_axis_data_TKEEP_int_regslice;
wire    regslice_both_s_axis_data_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_data_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_data_V_strb_V_U_apdone_blk;
wire   [1:0] s_axis_data_TSTRB_int_regslice;
wire    regslice_both_s_axis_data_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_data_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_data_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_data_TUSER_int_regslice;
wire    regslice_both_s_axis_data_V_user_V_U_vld_out;
wire    regslice_both_s_axis_data_V_user_V_U_ack_in;
wire    regslice_both_s_axis_data_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_data_TLAST_int_regslice;
wire    regslice_both_s_axis_data_V_last_V_U_vld_out;
wire    regslice_both_s_axis_data_V_last_V_U_ack_in;
wire    regslice_both_s_axis_data_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_data_TID_int_regslice;
wire    regslice_both_s_axis_data_V_id_V_U_vld_out;
wire    regslice_both_s_axis_data_V_id_V_U_ack_in;
wire    regslice_both_s_axis_data_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_data_TDEST_int_regslice;
wire    regslice_both_s_axis_data_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_data_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_start_reg = 1'b0;
end

fci_core_axis_to_fft_Pipeline_SAMPLE_LOOP grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_start),
    .ap_done(grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_done),
    .ap_idle(grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_idle),
    .ap_ready(grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_ready),
    .s_axis_data_TVALID(s_axis_data_TVALID_int_regslice),
    .xn_s_din(grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_xn_s_din),
    .xn_s_num_data_valid(2'd0),
    .xn_s_fifo_cap(2'd0),
    .xn_s_full_n(xn_s_full_n),
    .xn_s_write(grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_xn_s_write),
    .s_axis_data_TDATA(s_axis_data_TDATA_int_regslice),
    .s_axis_data_TREADY(grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_s_axis_data_TREADY),
    .s_axis_data_TKEEP(s_axis_data_TKEEP_int_regslice),
    .s_axis_data_TSTRB(s_axis_data_TSTRB_int_regslice),
    .s_axis_data_TUSER(s_axis_data_TUSER_int_regslice),
    .s_axis_data_TLAST(s_axis_data_TLAST_int_regslice),
    .s_axis_data_TID(s_axis_data_TID_int_regslice),
    .s_axis_data_TDEST(s_axis_data_TDEST_int_regslice)
);

fci_core_regslice_both #(
    .DataWidth( 16 ))
regslice_both_s_axis_data_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_data_TDATA),
    .vld_in(s_axis_data_TVALID),
    .ack_in(regslice_both_s_axis_data_V_data_V_U_ack_in),
    .data_out(s_axis_data_TDATA_int_regslice),
    .vld_out(s_axis_data_TVALID_int_regslice),
    .ack_out(s_axis_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_data_V_data_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 2 ))
regslice_both_s_axis_data_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_data_TKEEP),
    .vld_in(s_axis_data_TVALID),
    .ack_in(regslice_both_s_axis_data_V_keep_V_U_ack_in),
    .data_out(s_axis_data_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_data_V_keep_V_U_vld_out),
    .ack_out(s_axis_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_data_V_keep_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 2 ))
regslice_both_s_axis_data_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_data_TSTRB),
    .vld_in(s_axis_data_TVALID),
    .ack_in(regslice_both_s_axis_data_V_strb_V_U_ack_in),
    .data_out(s_axis_data_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_data_V_strb_V_U_vld_out),
    .ack_out(s_axis_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_data_V_strb_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_data_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_data_TUSER),
    .vld_in(s_axis_data_TVALID),
    .ack_in(regslice_both_s_axis_data_V_user_V_U_ack_in),
    .data_out(s_axis_data_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_data_V_user_V_U_vld_out),
    .ack_out(s_axis_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_data_V_user_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_data_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_data_TLAST),
    .vld_in(s_axis_data_TVALID),
    .ack_in(regslice_both_s_axis_data_V_last_V_U_ack_in),
    .data_out(s_axis_data_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_data_V_last_V_U_vld_out),
    .ack_out(s_axis_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_data_V_last_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_data_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_data_TID),
    .vld_in(s_axis_data_TVALID),
    .ack_in(regslice_both_s_axis_data_V_id_V_U_ack_in),
    .data_out(s_axis_data_TID_int_regslice),
    .vld_out(regslice_both_s_axis_data_V_id_V_U_vld_out),
    .ack_out(s_axis_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_data_V_id_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_data_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_data_TDEST),
    .vld_in(s_axis_data_TVALID),
    .ack_in(regslice_both_s_axis_data_V_dest_V_U_ack_in),
    .data_out(s_axis_data_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_data_V_dest_V_U_vld_out),
    .ack_out(s_axis_data_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_data_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_start_reg <= 1'b1;
        end else if ((grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_ready == 1'b1)) begin
            grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (config_s5_full_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_s5_blk_n = config_s5_full_n;
    end else begin
        config_s5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (config_s5_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        config_s5_write = 1'b1;
    end else begin
        config_s5_write = 1'b0;
    end
end

always @ (*) begin
    if (((grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_data_TREADY_int_regslice = grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_s_axis_data_TREADY;
    end else begin
        s_axis_data_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        xn_s_write = grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_xn_s_write;
    end else begin
        xn_s_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (config_s5_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (config_s5_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign config_s5_din = 8'd1;

assign grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_start = grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_ap_start_reg;

assign s_axis_data_TREADY = regslice_both_s_axis_data_V_data_V_U_ack_in;

assign start_out = real_start;

assign xn_s_din = grp_axis_to_fft_Pipeline_SAMPLE_LOOP_fu_54_xn_s_din;

endmodule //fci_core_axis_to_fft
