// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fci_core_fft_to_psa_Pipeline_BIN_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        xk_s_dout,
        xk_s_num_data_valid,
        xk_s_fifo_cap,
        xk_s_empty_n,
        xk_s_read,
        psa_l_lo_cast,
        psa_l_hi_cast,
        psa_w_lo_cast,
        zext_ln55,
        psa_w_V_out,
        psa_w_V_out_ap_vld,
        psa_l_V_out,
        psa_l_V_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] xk_s_dout;
input  [1:0] xk_s_num_data_valid;
input  [1:0] xk_s_fifo_cap;
input   xk_s_empty_n;
output   xk_s_read;
input  [9:0] psa_l_lo_cast;
input  [9:0] psa_l_hi_cast;
input  [9:0] psa_w_lo_cast;
input  [9:0] zext_ln55;
output  [27:0] psa_w_V_out;
output   psa_w_V_out_ap_vld;
output  [27:0] psa_l_V_out;
output   psa_l_V_out_ap_vld;

reg ap_idle;
reg xk_s_read;
reg psa_w_V_out_ap_vld;
reg psa_l_V_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln55_fu_158_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    xk_s_blk_n;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln1031_fu_170_p2;
reg   [0:0] icmp_ln1031_reg_401;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln1039_fu_176_p2;
reg   [0:0] icmp_ln1039_reg_406;
wire   [0:0] icmp_ln1031_1_fu_182_p2;
reg   [0:0] icmp_ln1031_1_reg_411;
wire   [0:0] icmp_ln1039_1_fu_188_p2;
reg   [0:0] icmp_ln1039_1_reg_416;
reg   [27:0] psa_l_V_fu_68;
wire   [27:0] psa_l_V_2_fu_319_p3;
wire    ap_loop_init;
reg   [27:0] psa_w_V_fu_72;
wire   [27:0] psa_w_V_2_fu_349_p3;
reg   [10:0] k_1_fu_76;
wire   [10:0] k_2_fu_164_p2;
reg   [10:0] ap_sig_allocacmp_k;
reg    ap_block_pp0_stage0_01001;
wire   [10:0] psa_l_lo_cast_cast_fu_136_p1;
wire   [10:0] psa_l_hi_cast_cast_fu_132_p1;
wire   [10:0] psa_w_lo_cast_cast_fu_128_p1;
wire   [10:0] zext_ln55_cast_fu_124_p1;
wire   [15:0] xk_M_real_fu_205_p1;
wire  signed [16:0] sext_ln813_fu_219_p1;
wire   [0:0] tmp_fu_223_p3;
wire   [16:0] wide_V_1_fu_231_p2;
wire   [16:0] select_ln7_fu_237_p3;
wire   [15:0] xk_M_imag_fu_209_p4;
wire  signed [16:0] sext_ln813_1_fu_253_p1;
wire   [0:0] tmp_1_fu_257_p3;
wire   [16:0] wide_V_3_fu_265_p2;
wire   [16:0] select_ln7_1_fu_271_p3;
wire   [17:0] shl_ln838_1_fu_279_p3;
wire   [17:0] shl_ln_fu_245_p3;
wire   [0:0] xor_ln1031_fu_293_p2;
wire   [0:0] xor_ln1039_fu_298_p2;
wire   [17:0] asdm_fu_287_p2;
wire   [27:0] zext_ln813_fu_309_p1;
wire   [0:0] and_ln59_fu_303_p2;
wire   [27:0] psa_l_V_1_fu_313_p2;
wire   [0:0] xor_ln1031_1_fu_327_p2;
wire   [0:0] xor_ln1039_1_fu_332_p2;
wire   [0:0] and_ln61_fu_337_p2;
wire   [27:0] psa_w_V_1_fu_343_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

fci_core_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln55_fu_158_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_1_fu_76 <= k_2_fu_164_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_1_fu_76 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            psa_l_V_fu_68 <= 28'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            psa_l_V_fu_68 <= psa_l_V_2_fu_319_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            psa_w_V_fu_72 <= 28'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            psa_w_V_fu_72 <= psa_w_V_2_fu_349_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_158_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1031_1_reg_411 <= icmp_ln1031_1_fu_182_p2;
        icmp_ln1031_reg_401 <= icmp_ln1031_fu_170_p2;
        icmp_ln1039_1_reg_416 <= icmp_ln1039_1_fu_188_p2;
        icmp_ln1039_reg_406 <= icmp_ln1039_fu_176_p2;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_158_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k = 11'd0;
    end else begin
        ap_sig_allocacmp_k = k_1_fu_76;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_158_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        psa_l_V_out_ap_vld = 1'b1;
    end else begin
        psa_l_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_158_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        psa_w_V_out_ap_vld = 1'b1;
    end else begin
        psa_w_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xk_s_blk_n = xk_s_empty_n;
    end else begin
        xk_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        xk_s_read = 1'b1;
    end else begin
        xk_s_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln59_fu_303_p2 = (xor_ln1039_fu_298_p2 & xor_ln1031_fu_293_p2);

assign and_ln61_fu_337_p2 = (xor_ln1039_1_fu_332_p2 & xor_ln1031_1_fu_327_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((xk_s_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((xk_s_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((xk_s_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (xk_s_empty_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign asdm_fu_287_p2 = (shl_ln838_1_fu_279_p3 + shl_ln_fu_245_p3);

assign icmp_ln1031_1_fu_182_p2 = ((ap_sig_allocacmp_k < psa_w_lo_cast_cast_fu_128_p1) ? 1'b1 : 1'b0);

assign icmp_ln1031_fu_170_p2 = ((ap_sig_allocacmp_k < psa_l_lo_cast_cast_fu_136_p1) ? 1'b1 : 1'b0);

assign icmp_ln1039_1_fu_188_p2 = ((zext_ln55_cast_fu_124_p1 < ap_sig_allocacmp_k) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_176_p2 = ((psa_l_hi_cast_cast_fu_132_p1 < ap_sig_allocacmp_k) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_158_p2 = ((ap_sig_allocacmp_k == 11'd1024) ? 1'b1 : 1'b0);

assign k_2_fu_164_p2 = (ap_sig_allocacmp_k + 11'd1);

assign psa_l_V_1_fu_313_p2 = (psa_l_V_fu_68 + zext_ln813_fu_309_p1);

assign psa_l_V_2_fu_319_p3 = ((and_ln59_fu_303_p2[0:0] == 1'b1) ? psa_l_V_1_fu_313_p2 : psa_l_V_fu_68);

assign psa_l_V_out = psa_l_V_fu_68;

assign psa_l_hi_cast_cast_fu_132_p1 = psa_l_hi_cast;

assign psa_l_lo_cast_cast_fu_136_p1 = psa_l_lo_cast;

assign psa_w_V_1_fu_343_p2 = (psa_w_V_fu_72 + zext_ln813_fu_309_p1);

assign psa_w_V_2_fu_349_p3 = ((and_ln61_fu_337_p2[0:0] == 1'b1) ? psa_w_V_1_fu_343_p2 : psa_w_V_fu_72);

assign psa_w_V_out = psa_w_V_fu_72;

assign psa_w_lo_cast_cast_fu_128_p1 = psa_w_lo_cast;

assign select_ln7_1_fu_271_p3 = ((tmp_1_fu_257_p3[0:0] == 1'b1) ? wide_V_3_fu_265_p2 : sext_ln813_1_fu_253_p1);

assign select_ln7_fu_237_p3 = ((tmp_fu_223_p3[0:0] == 1'b1) ? wide_V_1_fu_231_p2 : sext_ln813_fu_219_p1);

assign sext_ln813_1_fu_253_p1 = $signed(xk_M_imag_fu_209_p4);

assign sext_ln813_fu_219_p1 = $signed(xk_M_real_fu_205_p1);

assign shl_ln838_1_fu_279_p3 = {{select_ln7_1_fu_271_p3}, {1'd0}};

assign shl_ln_fu_245_p3 = {{select_ln7_fu_237_p3}, {1'd0}};

assign tmp_1_fu_257_p3 = xk_s_dout[32'd31];

assign tmp_fu_223_p3 = xk_s_dout[32'd15];

assign wide_V_1_fu_231_p2 = ($signed(17'd0) - $signed(sext_ln813_fu_219_p1));

assign wide_V_3_fu_265_p2 = ($signed(17'd0) - $signed(sext_ln813_1_fu_253_p1));

assign xk_M_imag_fu_209_p4 = {{xk_s_dout[31:16]}};

assign xk_M_real_fu_205_p1 = xk_s_dout[15:0];

assign xor_ln1031_1_fu_327_p2 = (icmp_ln1031_1_reg_411 ^ 1'd1);

assign xor_ln1031_fu_293_p2 = (icmp_ln1031_reg_401 ^ 1'd1);

assign xor_ln1039_1_fu_332_p2 = (icmp_ln1039_1_reg_416 ^ 1'd1);

assign xor_ln1039_fu_298_p2 = (icmp_ln1039_reg_406 ^ 1'd1);

assign zext_ln55_cast_fu_124_p1 = zext_ln55;

assign zext_ln813_fu_309_p1 = asdm_fu_287_p2;

endmodule //fci_core_fft_to_psa_Pipeline_BIN_LOOP
