// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fci_core_fft_to_psa (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        xk_s_dout,
        xk_s_num_data_valid,
        xk_s_fifo_cap,
        xk_s_empty_n,
        xk_s_read,
        status_s4_dout,
        status_s4_num_data_valid,
        status_s4_fifo_cap,
        status_s4_empty_n,
        status_s4_read,
        psa_l_lo_s_dout,
        psa_l_lo_s_empty_n,
        psa_l_lo_s_read,
        psa_l_hi_s_dout,
        psa_l_hi_s_empty_n,
        psa_l_hi_s_read,
        psa_w_lo_s_dout,
        psa_w_lo_s_empty_n,
        psa_w_lo_s_read,
        psa_w_hi_s_dout,
        psa_w_hi_s_empty_n,
        psa_w_hi_s_read,
        m_axis_result_TDATA,
        m_axis_result_TVALID,
        m_axis_result_TREADY,
        m_axis_result_TKEEP,
        m_axis_result_TSTRB,
        m_axis_result_TUSER,
        m_axis_result_TLAST,
        m_axis_result_TID,
        m_axis_result_TDEST
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] xk_s_dout;
input  [1:0] xk_s_num_data_valid;
input  [1:0] xk_s_fifo_cap;
input   xk_s_empty_n;
output   xk_s_read;
input  [7:0] status_s4_dout;
input  [1:0] status_s4_num_data_valid;
input  [1:0] status_s4_fifo_cap;
input   status_s4_empty_n;
output   status_s4_read;
input  [9:0] psa_l_lo_s_dout;
input   psa_l_lo_s_empty_n;
output   psa_l_lo_s_read;
input  [9:0] psa_l_hi_s_dout;
input   psa_l_hi_s_empty_n;
output   psa_l_hi_s_read;
input  [9:0] psa_w_lo_s_dout;
input   psa_w_lo_s_empty_n;
output   psa_w_lo_s_read;
input  [9:0] psa_w_hi_s_dout;
input   psa_w_hi_s_empty_n;
output   psa_w_hi_s_read;
output  [31:0] m_axis_result_TDATA;
output   m_axis_result_TVALID;
input   m_axis_result_TREADY;
output  [3:0] m_axis_result_TKEEP;
output  [3:0] m_axis_result_TSTRB;
output  [0:0] m_axis_result_TUSER;
output  [0:0] m_axis_result_TLAST;
output  [0:0] m_axis_result_TID;
output  [0:0] m_axis_result_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg xk_s_read;
reg status_s4_read;
reg psa_l_lo_s_read;
reg psa_l_hi_s_read;
reg psa_w_lo_s_read;
reg psa_w_hi_s_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    status_s4_blk_n;
wire    ap_CS_fsm_state6;
reg    psa_l_lo_s_blk_n;
reg    psa_l_hi_s_blk_n;
reg    psa_w_lo_s_blk_n;
reg    psa_w_hi_s_blk_n;
reg    m_axis_result_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [9:0] psa_l_lo_V_reg_176;
reg   [9:0] psa_l_hi_V_reg_181;
reg   [9:0] psa_w_lo_V_reg_186;
reg   [9:0] psa_w_hi_V_reg_191;
wire   [31:0] zext_ln368_fu_151_p1;
wire   [31:0] zext_ln368_1_fu_159_p1;
wire    grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_start;
wire    grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_done;
wire    grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_idle;
wire    grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_ready;
wire    grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_xk_s_read;
wire   [27:0] grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_w_V_out;
wire    grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_w_V_out_ap_vld;
wire   [27:0] grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_l_V_out;
wire    grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_l_V_out_ap_vld;
reg    grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_block_state1;
wire    regslice_both_m_axis_result_V_data_V_U_apdone_blk;
reg    ap_block_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg   [31:0] m_axis_result_TDATA_int_regslice;
reg    m_axis_result_TVALID_int_regslice;
wire    m_axis_result_TREADY_int_regslice;
wire    regslice_both_m_axis_result_V_data_V_U_vld_out;
wire    regslice_both_m_axis_result_V_keep_V_U_apdone_blk;
wire    regslice_both_m_axis_result_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_result_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_result_V_strb_V_U_apdone_blk;
wire    regslice_both_m_axis_result_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_result_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_result_V_user_V_U_apdone_blk;
wire    regslice_both_m_axis_result_V_user_V_U_ack_in_dummy;
wire    regslice_both_m_axis_result_V_user_V_U_vld_out;
wire    regslice_both_m_axis_result_V_last_V_U_apdone_blk;
reg   [0:0] m_axis_result_TLAST_int_regslice;
wire    regslice_both_m_axis_result_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_result_V_last_V_U_vld_out;
wire    regslice_both_m_axis_result_V_id_V_U_apdone_blk;
wire    regslice_both_m_axis_result_V_id_V_U_ack_in_dummy;
wire    regslice_both_m_axis_result_V_id_V_U_vld_out;
wire    regslice_both_m_axis_result_V_dest_V_U_apdone_blk;
wire    regslice_both_m_axis_result_V_dest_V_U_ack_in_dummy;
wire    regslice_both_m_axis_result_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_start_reg = 1'b0;
end

fci_core_fft_to_psa_Pipeline_BIN_LOOP grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_start),
    .ap_done(grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_done),
    .ap_idle(grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_idle),
    .ap_ready(grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_ready),
    .xk_s_dout(xk_s_dout),
    .xk_s_num_data_valid(2'd0),
    .xk_s_fifo_cap(2'd0),
    .xk_s_empty_n(xk_s_empty_n),
    .xk_s_read(grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_xk_s_read),
    .psa_l_lo_V_cast(psa_l_lo_V_reg_176),
    .psa_l_hi_V_cast(psa_l_hi_V_reg_181),
    .psa_w_lo_V_cast(psa_w_lo_V_reg_186),
    .zext_ln59(psa_w_hi_V_reg_191),
    .psa_w_V_out(grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_w_V_out),
    .psa_w_V_out_ap_vld(grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_w_V_out_ap_vld),
    .psa_l_V_out(grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_l_V_out),
    .psa_l_V_out_ap_vld(grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_l_V_out_ap_vld)
);

fci_core_regslice_both #(
    .DataWidth( 32 ))
regslice_both_m_axis_result_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_result_TDATA_int_regslice),
    .vld_in(m_axis_result_TVALID_int_regslice),
    .ack_in(m_axis_result_TREADY_int_regslice),
    .data_out(m_axis_result_TDATA),
    .vld_out(regslice_both_m_axis_result_V_data_V_U_vld_out),
    .ack_out(m_axis_result_TREADY),
    .apdone_blk(regslice_both_m_axis_result_V_data_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_result_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(4'd15),
    .vld_in(m_axis_result_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_result_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_result_TKEEP),
    .vld_out(regslice_both_m_axis_result_V_keep_V_U_vld_out),
    .ack_out(m_axis_result_TREADY),
    .apdone_blk(regslice_both_m_axis_result_V_keep_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_result_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(4'd15),
    .vld_in(m_axis_result_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_result_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_result_TSTRB),
    .vld_out(regslice_both_m_axis_result_V_strb_V_U_vld_out),
    .ack_out(m_axis_result_TREADY),
    .apdone_blk(regslice_both_m_axis_result_V_strb_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_result_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(1'd0),
    .vld_in(m_axis_result_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_result_V_user_V_U_ack_in_dummy),
    .data_out(m_axis_result_TUSER),
    .vld_out(regslice_both_m_axis_result_V_user_V_U_vld_out),
    .ack_out(m_axis_result_TREADY),
    .apdone_blk(regslice_both_m_axis_result_V_user_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_result_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_result_TLAST_int_regslice),
    .vld_in(m_axis_result_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_result_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_result_TLAST),
    .vld_out(regslice_both_m_axis_result_V_last_V_U_vld_out),
    .ack_out(m_axis_result_TREADY),
    .apdone_blk(regslice_both_m_axis_result_V_last_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_result_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(1'd0),
    .vld_in(m_axis_result_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_result_V_id_V_U_ack_in_dummy),
    .data_out(m_axis_result_TID),
    .vld_out(regslice_both_m_axis_result_V_id_V_U_vld_out),
    .ack_out(m_axis_result_TREADY),
    .apdone_blk(regslice_both_m_axis_result_V_id_V_U_apdone_blk)
);

fci_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_result_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(1'd0),
    .vld_in(m_axis_result_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_result_V_dest_V_U_ack_in_dummy),
    .data_out(m_axis_result_TDEST),
    .vld_out(regslice_both_m_axis_result_V_dest_V_U_vld_out),
    .ack_out(m_axis_result_TREADY),
    .apdone_blk(regslice_both_m_axis_result_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((status_s4_empty_n == 1'b0) | (m_axis_result_TREADY_int_regslice == 1'b0) | (regslice_both_m_axis_result_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_start_reg <= 1'b1;
        end else if ((grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_ready == 1'b1)) begin
            grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        psa_l_hi_V_reg_181 <= psa_l_hi_s_dout;
        psa_l_lo_V_reg_176 <= psa_l_lo_s_dout;
        psa_w_hi_V_reg_191 <= psa_w_hi_s_dout;
        psa_w_lo_V_reg_186 <= psa_w_lo_s_dout;
    end
end

always @ (*) begin
    if (((psa_w_hi_s_empty_n == 1'b0) | (psa_w_lo_s_empty_n == 1'b0) | (psa_l_hi_s_empty_n == 1'b0) | (psa_l_lo_s_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axis_result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axis_result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((status_s4_empty_n == 1'b0) | (m_axis_result_TREADY_int_regslice == 1'b0) | (regslice_both_m_axis_result_V_data_V_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((status_s4_empty_n == 1'b0) | (m_axis_result_TREADY_int_regslice == 1'b0) | (regslice_both_m_axis_result_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((status_s4_empty_n == 1'b0) | (m_axis_result_TREADY_int_regslice == 1'b0) | (regslice_both_m_axis_result_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state6))) begin
        m_axis_result_TDATA_blk_n = m_axis_result_TREADY_int_regslice;
    end else begin
        m_axis_result_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((m_axis_result_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            m_axis_result_TDATA_int_regslice = zext_ln368_1_fu_159_p1;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            m_axis_result_TDATA_int_regslice = zext_ln368_fu_151_p1;
        end else begin
            m_axis_result_TDATA_int_regslice = 'bx;
        end
    end else begin
        m_axis_result_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((m_axis_result_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            m_axis_result_TLAST_int_regslice = 1'd1;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            m_axis_result_TLAST_int_regslice = 1'd0;
        end else begin
            m_axis_result_TLAST_int_regslice = 'bx;
        end
    end else begin
        m_axis_result_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((m_axis_result_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((m_axis_result_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        m_axis_result_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_result_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        psa_l_hi_s_blk_n = psa_l_hi_s_empty_n;
    end else begin
        psa_l_hi_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((psa_w_hi_s_empty_n == 1'b0) | (psa_w_lo_s_empty_n == 1'b0) | (psa_l_hi_s_empty_n == 1'b0) | (psa_l_lo_s_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        psa_l_hi_s_read = 1'b1;
    end else begin
        psa_l_hi_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        psa_l_lo_s_blk_n = psa_l_lo_s_empty_n;
    end else begin
        psa_l_lo_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((psa_w_hi_s_empty_n == 1'b0) | (psa_w_lo_s_empty_n == 1'b0) | (psa_l_hi_s_empty_n == 1'b0) | (psa_l_lo_s_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        psa_l_lo_s_read = 1'b1;
    end else begin
        psa_l_lo_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        psa_w_hi_s_blk_n = psa_w_hi_s_empty_n;
    end else begin
        psa_w_hi_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((psa_w_hi_s_empty_n == 1'b0) | (psa_w_lo_s_empty_n == 1'b0) | (psa_l_hi_s_empty_n == 1'b0) | (psa_l_lo_s_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        psa_w_hi_s_read = 1'b1;
    end else begin
        psa_w_hi_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        psa_w_lo_s_blk_n = psa_w_lo_s_empty_n;
    end else begin
        psa_w_lo_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((psa_w_hi_s_empty_n == 1'b0) | (psa_w_lo_s_empty_n == 1'b0) | (psa_l_hi_s_empty_n == 1'b0) | (psa_l_lo_s_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        psa_w_lo_s_read = 1'b1;
    end else begin
        psa_w_lo_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        status_s4_blk_n = status_s4_empty_n;
    end else begin
        status_s4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((status_s4_empty_n == 1'b0) | (m_axis_result_TREADY_int_regslice == 1'b0) | (regslice_both_m_axis_result_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state6))) begin
        status_s4_read = 1'b1;
    end else begin
        status_s4_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        xk_s_read = grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_xk_s_read;
    end else begin
        xk_s_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((psa_w_hi_s_empty_n == 1'b0) | (psa_w_lo_s_empty_n == 1'b0) | (psa_l_hi_s_empty_n == 1'b0) | (psa_l_lo_s_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((m_axis_result_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((m_axis_result_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((status_s4_empty_n == 1'b0) | (m_axis_result_TREADY_int_regslice == 1'b0) | (regslice_both_m_axis_result_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((psa_w_hi_s_empty_n == 1'b0) | (psa_w_lo_s_empty_n == 1'b0) | (psa_l_hi_s_empty_n == 1'b0) | (psa_l_lo_s_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((status_s4_empty_n == 1'b0) | (m_axis_result_TREADY_int_regslice == 1'b0) | (regslice_both_m_axis_result_V_data_V_U_apdone_blk == 1'b1));
end

assign grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_start = grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_ap_start_reg;

assign m_axis_result_TVALID = regslice_both_m_axis_result_V_data_V_U_vld_out;

assign zext_ln368_1_fu_159_p1 = grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_w_V_out;

assign zext_ln368_fu_151_p1 = grp_fft_to_psa_Pipeline_BIN_LOOP_fu_136_psa_l_V_out;

endmodule //fci_core_fft_to_psa
