-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fci_core is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    s_axis_data_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    s_axis_data_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    s_axis_data_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    s_axis_data_TUSER : IN STD_LOGIC_VECTOR (63 downto 0);
    s_axis_data_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_data_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_data_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_result_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_result_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_result_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_result_TUSER : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axis_result_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_result_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_result_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axis_data_TVALID : IN STD_LOGIC;
    s_axis_data_TREADY : OUT STD_LOGIC;
    m_axis_result_TVALID : OUT STD_LOGIC;
    m_axis_result_TREADY : IN STD_LOGIC );
end;


architecture behav of fci_core is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fci_core_fci_core,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.600000,HLS_SYN_LAT=3200,HLS_SYN_TPT=3197,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=11169,HLS_SYN_LUT=9520,HLS_VERSION=2022_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal psa_l_lo : STD_LOGIC_VECTOR (9 downto 0);
    signal psa_l_hi : STD_LOGIC_VECTOR (9 downto 0);
    signal psa_w_lo : STD_LOGIC_VECTOR (9 downto 0);
    signal psa_w_hi : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_psa_l_lo_c_din : STD_LOGIC_VECTOR (9 downto 0);
    signal entry_proc_U0_psa_l_lo_c_write : STD_LOGIC;
    signal entry_proc_U0_psa_l_hi_c_din : STD_LOGIC_VECTOR (9 downto 0);
    signal entry_proc_U0_psa_l_hi_c_write : STD_LOGIC;
    signal entry_proc_U0_psa_w_lo_c_din : STD_LOGIC_VECTOR (9 downto 0);
    signal entry_proc_U0_psa_w_lo_c_write : STD_LOGIC;
    signal entry_proc_U0_psa_w_hi_c_din : STD_LOGIC_VECTOR (9 downto 0);
    signal entry_proc_U0_psa_w_hi_c_write : STD_LOGIC;
    signal axis_to_fft_U0_ap_start : STD_LOGIC;
    signal axis_to_fft_U0_ap_done : STD_LOGIC;
    signal axis_to_fft_U0_ap_continue : STD_LOGIC;
    signal axis_to_fft_U0_ap_idle : STD_LOGIC;
    signal axis_to_fft_U0_ap_ready : STD_LOGIC;
    signal axis_to_fft_U0_start_out : STD_LOGIC;
    signal axis_to_fft_U0_start_write : STD_LOGIC;
    signal axis_to_fft_U0_s_axis_data_TREADY : STD_LOGIC;
    signal axis_to_fft_U0_xn_s_din : STD_LOGIC_VECTOR (31 downto 0);
    signal axis_to_fft_U0_xn_s_write : STD_LOGIC;
    signal axis_to_fft_U0_config_s18_din : STD_LOGIC_VECTOR (7 downto 0);
    signal axis_to_fft_U0_config_s18_write : STD_LOGIC;
    signal axis_to_fft_U0_tag_s19_din : STD_LOGIC_VECTOR (63 downto 0);
    signal axis_to_fft_U0_tag_s19_write : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_start : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_done : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_continue : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_idle : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_ready : STD_LOGIC;
    signal fft_fci_fft_config_U0_xn_s_read : STD_LOGIC;
    signal fft_fci_fft_config_U0_xk_s_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_fci_fft_config_U0_xk_s_write : STD_LOGIC;
    signal fft_fci_fft_config_U0_status_s17_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_fci_fft_config_U0_status_s17_write : STD_LOGIC;
    signal fft_fci_fft_config_U0_config_s18_read : STD_LOGIC;
    signal fft_to_psa_U0_ap_start : STD_LOGIC;
    signal fft_to_psa_U0_ap_done : STD_LOGIC;
    signal fft_to_psa_U0_ap_continue : STD_LOGIC;
    signal fft_to_psa_U0_ap_idle : STD_LOGIC;
    signal fft_to_psa_U0_ap_ready : STD_LOGIC;
    signal fft_to_psa_U0_xk_s_read : STD_LOGIC;
    signal fft_to_psa_U0_status_s17_read : STD_LOGIC;
    signal fft_to_psa_U0_psa_l_lo_read : STD_LOGIC;
    signal fft_to_psa_U0_psa_l_hi_read : STD_LOGIC;
    signal fft_to_psa_U0_psa_w_lo_read : STD_LOGIC;
    signal fft_to_psa_U0_psa_w_hi_read : STD_LOGIC;
    signal fft_to_psa_U0_m_axis_result_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_to_psa_U0_m_axis_result_TVALID : STD_LOGIC;
    signal fft_to_psa_U0_m_axis_result_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal fft_to_psa_U0_m_axis_result_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal fft_to_psa_U0_m_axis_result_TUSER : STD_LOGIC_VECTOR (63 downto 0);
    signal fft_to_psa_U0_m_axis_result_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal fft_to_psa_U0_m_axis_result_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal fft_to_psa_U0_m_axis_result_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal fft_to_psa_U0_tag_s19_read : STD_LOGIC;
    signal psa_l_lo_c_full_n : STD_LOGIC;
    signal psa_l_lo_c_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal psa_l_lo_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal psa_l_lo_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal psa_l_lo_c_empty_n : STD_LOGIC;
    signal psa_l_hi_c_full_n : STD_LOGIC;
    signal psa_l_hi_c_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal psa_l_hi_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal psa_l_hi_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal psa_l_hi_c_empty_n : STD_LOGIC;
    signal psa_w_lo_c_full_n : STD_LOGIC;
    signal psa_w_lo_c_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal psa_w_lo_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal psa_w_lo_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal psa_w_lo_c_empty_n : STD_LOGIC;
    signal psa_w_hi_c_full_n : STD_LOGIC;
    signal psa_w_hi_c_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal psa_w_hi_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal psa_w_hi_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal psa_w_hi_c_empty_n : STD_LOGIC;
    signal xn_s_full_n : STD_LOGIC;
    signal xn_s_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal xn_s_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal xn_s_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal xn_s_empty_n : STD_LOGIC;
    signal config_s_full_n : STD_LOGIC;
    signal config_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal config_s_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal config_s_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal config_s_empty_n : STD_LOGIC;
    signal tag_s_full_n : STD_LOGIC;
    signal tag_s_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal tag_s_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal tag_s_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal tag_s_empty_n : STD_LOGIC;
    signal xk_s_full_n : STD_LOGIC;
    signal xk_s_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal xk_s_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal xk_s_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal xk_s_empty_n : STD_LOGIC;
    signal status_s_full_n : STD_LOGIC;
    signal status_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal status_s_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal status_s_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal status_s_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_axis_to_fft_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_axis_to_fft_U0_ap_ready : STD_LOGIC;
    signal start_for_fft_to_psa_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_to_psa_U0_full_n : STD_LOGIC;
    signal start_for_fft_to_psa_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_to_psa_U0_empty_n : STD_LOGIC;
    signal start_for_fft_fci_fft_config_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_fci_fft_config_U0_full_n : STD_LOGIC;
    signal start_for_fft_fci_fft_config_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_fci_fft_config_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fci_core_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        psa_l_lo : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_l_lo_c_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        psa_l_lo_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_l_lo_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_l_lo_c_full_n : IN STD_LOGIC;
        psa_l_lo_c_write : OUT STD_LOGIC;
        psa_l_hi : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_l_hi_c_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        psa_l_hi_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_l_hi_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_l_hi_c_full_n : IN STD_LOGIC;
        psa_l_hi_c_write : OUT STD_LOGIC;
        psa_w_lo : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_w_lo_c_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        psa_w_lo_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_w_lo_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_w_lo_c_full_n : IN STD_LOGIC;
        psa_w_lo_c_write : OUT STD_LOGIC;
        psa_w_hi : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_w_hi_c_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        psa_w_hi_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_w_hi_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_w_hi_c_full_n : IN STD_LOGIC;
        psa_w_hi_c_write : OUT STD_LOGIC );
    end component;


    component fci_core_axis_to_fft IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        s_axis_data_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        s_axis_data_TVALID : IN STD_LOGIC;
        s_axis_data_TREADY : OUT STD_LOGIC;
        s_axis_data_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
        s_axis_data_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
        s_axis_data_TUSER : IN STD_LOGIC_VECTOR (63 downto 0);
        s_axis_data_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_data_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_data_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        xn_s_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xn_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        xn_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        xn_s_full_n : IN STD_LOGIC;
        xn_s_write : OUT STD_LOGIC;
        config_s18_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        config_s18_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        config_s18_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        config_s18_full_n : IN STD_LOGIC;
        config_s18_write : OUT STD_LOGIC;
        tag_s19_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        tag_s19_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        tag_s19_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        tag_s19_full_n : IN STD_LOGIC;
        tag_s19_write : OUT STD_LOGIC );
    end component;


    component fci_core_fft_fci_fft_config_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        xn_s_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        xn_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        xn_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        xn_s_empty_n : IN STD_LOGIC;
        xn_s_read : OUT STD_LOGIC;
        xk_s_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xk_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        xk_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        xk_s_full_n : IN STD_LOGIC;
        xk_s_write : OUT STD_LOGIC;
        status_s17_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_s17_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        status_s17_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        status_s17_full_n : IN STD_LOGIC;
        status_s17_write : OUT STD_LOGIC;
        config_s18_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        config_s18_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        config_s18_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        config_s18_empty_n : IN STD_LOGIC;
        config_s18_read : OUT STD_LOGIC );
    end component;


    component fci_core_fft_to_psa IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        xk_s_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        xk_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        xk_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        xk_s_empty_n : IN STD_LOGIC;
        xk_s_read : OUT STD_LOGIC;
        status_s17_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        status_s17_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        status_s17_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        status_s17_empty_n : IN STD_LOGIC;
        status_s17_read : OUT STD_LOGIC;
        psa_l_lo_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_l_lo_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_l_lo_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_l_lo_empty_n : IN STD_LOGIC;
        psa_l_lo_read : OUT STD_LOGIC;
        psa_l_hi_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_l_hi_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_l_hi_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_l_hi_empty_n : IN STD_LOGIC;
        psa_l_hi_read : OUT STD_LOGIC;
        psa_w_lo_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_w_lo_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_w_lo_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_w_lo_empty_n : IN STD_LOGIC;
        psa_w_lo_read : OUT STD_LOGIC;
        psa_w_hi_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_w_hi_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_w_hi_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        psa_w_hi_empty_n : IN STD_LOGIC;
        psa_w_hi_read : OUT STD_LOGIC;
        m_axis_result_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axis_result_TVALID : OUT STD_LOGIC;
        m_axis_result_TREADY : IN STD_LOGIC;
        m_axis_result_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_result_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_result_TUSER : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axis_result_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_result_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_result_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        tag_s19_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        tag_s19_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        tag_s19_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        tag_s19_empty_n : IN STD_LOGIC;
        tag_s19_read : OUT STD_LOGIC );
    end component;


    component fci_core_fifo_w10_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (9 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (9 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fci_core_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fci_core_fifo_w8_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fci_core_fifo_w64_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fci_core_start_for_fft_to_psa_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fci_core_start_for_fft_fci_fft_config_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fci_core_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        psa_l_lo : OUT STD_LOGIC_VECTOR (9 downto 0);
        psa_l_hi : OUT STD_LOGIC_VECTOR (9 downto 0);
        psa_w_lo : OUT STD_LOGIC_VECTOR (9 downto 0);
        psa_w_hi : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component fci_core_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        psa_l_lo => psa_l_lo,
        psa_l_hi => psa_l_hi,
        psa_w_lo => psa_w_lo,
        psa_w_hi => psa_w_hi,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    entry_proc_U0 : component fci_core_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_fft_to_psa_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        psa_l_lo => psa_l_lo,
        psa_l_lo_c_din => entry_proc_U0_psa_l_lo_c_din,
        psa_l_lo_c_num_data_valid => psa_l_lo_c_num_data_valid,
        psa_l_lo_c_fifo_cap => psa_l_lo_c_fifo_cap,
        psa_l_lo_c_full_n => psa_l_lo_c_full_n,
        psa_l_lo_c_write => entry_proc_U0_psa_l_lo_c_write,
        psa_l_hi => psa_l_hi,
        psa_l_hi_c_din => entry_proc_U0_psa_l_hi_c_din,
        psa_l_hi_c_num_data_valid => psa_l_hi_c_num_data_valid,
        psa_l_hi_c_fifo_cap => psa_l_hi_c_fifo_cap,
        psa_l_hi_c_full_n => psa_l_hi_c_full_n,
        psa_l_hi_c_write => entry_proc_U0_psa_l_hi_c_write,
        psa_w_lo => psa_w_lo,
        psa_w_lo_c_din => entry_proc_U0_psa_w_lo_c_din,
        psa_w_lo_c_num_data_valid => psa_w_lo_c_num_data_valid,
        psa_w_lo_c_fifo_cap => psa_w_lo_c_fifo_cap,
        psa_w_lo_c_full_n => psa_w_lo_c_full_n,
        psa_w_lo_c_write => entry_proc_U0_psa_w_lo_c_write,
        psa_w_hi => psa_w_hi,
        psa_w_hi_c_din => entry_proc_U0_psa_w_hi_c_din,
        psa_w_hi_c_num_data_valid => psa_w_hi_c_num_data_valid,
        psa_w_hi_c_fifo_cap => psa_w_hi_c_fifo_cap,
        psa_w_hi_c_full_n => psa_w_hi_c_full_n,
        psa_w_hi_c_write => entry_proc_U0_psa_w_hi_c_write);

    axis_to_fft_U0 : component fci_core_axis_to_fft
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => axis_to_fft_U0_ap_start,
        start_full_n => start_for_fft_fci_fft_config_U0_full_n,
        ap_done => axis_to_fft_U0_ap_done,
        ap_continue => axis_to_fft_U0_ap_continue,
        ap_idle => axis_to_fft_U0_ap_idle,
        ap_ready => axis_to_fft_U0_ap_ready,
        start_out => axis_to_fft_U0_start_out,
        start_write => axis_to_fft_U0_start_write,
        s_axis_data_TDATA => s_axis_data_TDATA,
        s_axis_data_TVALID => s_axis_data_TVALID,
        s_axis_data_TREADY => axis_to_fft_U0_s_axis_data_TREADY,
        s_axis_data_TKEEP => s_axis_data_TKEEP,
        s_axis_data_TSTRB => s_axis_data_TSTRB,
        s_axis_data_TUSER => s_axis_data_TUSER,
        s_axis_data_TLAST => s_axis_data_TLAST,
        s_axis_data_TID => s_axis_data_TID,
        s_axis_data_TDEST => s_axis_data_TDEST,
        xn_s_din => axis_to_fft_U0_xn_s_din,
        xn_s_num_data_valid => xn_s_num_data_valid,
        xn_s_fifo_cap => xn_s_fifo_cap,
        xn_s_full_n => xn_s_full_n,
        xn_s_write => axis_to_fft_U0_xn_s_write,
        config_s18_din => axis_to_fft_U0_config_s18_din,
        config_s18_num_data_valid => config_s_num_data_valid,
        config_s18_fifo_cap => config_s_fifo_cap,
        config_s18_full_n => config_s_full_n,
        config_s18_write => axis_to_fft_U0_config_s18_write,
        tag_s19_din => axis_to_fft_U0_tag_s19_din,
        tag_s19_num_data_valid => tag_s_num_data_valid,
        tag_s19_fifo_cap => tag_s_fifo_cap,
        tag_s19_full_n => tag_s_full_n,
        tag_s19_write => axis_to_fft_U0_tag_s19_write);

    fft_fci_fft_config_U0 : component fci_core_fft_fci_fft_config_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => fft_fci_fft_config_U0_ap_start,
        ap_done => fft_fci_fft_config_U0_ap_done,
        ap_continue => fft_fci_fft_config_U0_ap_continue,
        ap_idle => fft_fci_fft_config_U0_ap_idle,
        ap_ready => fft_fci_fft_config_U0_ap_ready,
        xn_s_dout => xn_s_dout,
        xn_s_num_data_valid => xn_s_num_data_valid,
        xn_s_fifo_cap => xn_s_fifo_cap,
        xn_s_empty_n => xn_s_empty_n,
        xn_s_read => fft_fci_fft_config_U0_xn_s_read,
        xk_s_din => fft_fci_fft_config_U0_xk_s_din,
        xk_s_num_data_valid => xk_s_num_data_valid,
        xk_s_fifo_cap => xk_s_fifo_cap,
        xk_s_full_n => xk_s_full_n,
        xk_s_write => fft_fci_fft_config_U0_xk_s_write,
        status_s17_din => fft_fci_fft_config_U0_status_s17_din,
        status_s17_num_data_valid => status_s_num_data_valid,
        status_s17_fifo_cap => status_s_fifo_cap,
        status_s17_full_n => status_s_full_n,
        status_s17_write => fft_fci_fft_config_U0_status_s17_write,
        config_s18_dout => config_s_dout,
        config_s18_num_data_valid => config_s_num_data_valid,
        config_s18_fifo_cap => config_s_fifo_cap,
        config_s18_empty_n => config_s_empty_n,
        config_s18_read => fft_fci_fft_config_U0_config_s18_read);

    fft_to_psa_U0 : component fci_core_fft_to_psa
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => fft_to_psa_U0_ap_start,
        ap_done => fft_to_psa_U0_ap_done,
        ap_continue => fft_to_psa_U0_ap_continue,
        ap_idle => fft_to_psa_U0_ap_idle,
        ap_ready => fft_to_psa_U0_ap_ready,
        xk_s_dout => xk_s_dout,
        xk_s_num_data_valid => xk_s_num_data_valid,
        xk_s_fifo_cap => xk_s_fifo_cap,
        xk_s_empty_n => xk_s_empty_n,
        xk_s_read => fft_to_psa_U0_xk_s_read,
        status_s17_dout => status_s_dout,
        status_s17_num_data_valid => status_s_num_data_valid,
        status_s17_fifo_cap => status_s_fifo_cap,
        status_s17_empty_n => status_s_empty_n,
        status_s17_read => fft_to_psa_U0_status_s17_read,
        psa_l_lo_dout => psa_l_lo_c_dout,
        psa_l_lo_num_data_valid => psa_l_lo_c_num_data_valid,
        psa_l_lo_fifo_cap => psa_l_lo_c_fifo_cap,
        psa_l_lo_empty_n => psa_l_lo_c_empty_n,
        psa_l_lo_read => fft_to_psa_U0_psa_l_lo_read,
        psa_l_hi_dout => psa_l_hi_c_dout,
        psa_l_hi_num_data_valid => psa_l_hi_c_num_data_valid,
        psa_l_hi_fifo_cap => psa_l_hi_c_fifo_cap,
        psa_l_hi_empty_n => psa_l_hi_c_empty_n,
        psa_l_hi_read => fft_to_psa_U0_psa_l_hi_read,
        psa_w_lo_dout => psa_w_lo_c_dout,
        psa_w_lo_num_data_valid => psa_w_lo_c_num_data_valid,
        psa_w_lo_fifo_cap => psa_w_lo_c_fifo_cap,
        psa_w_lo_empty_n => psa_w_lo_c_empty_n,
        psa_w_lo_read => fft_to_psa_U0_psa_w_lo_read,
        psa_w_hi_dout => psa_w_hi_c_dout,
        psa_w_hi_num_data_valid => psa_w_hi_c_num_data_valid,
        psa_w_hi_fifo_cap => psa_w_hi_c_fifo_cap,
        psa_w_hi_empty_n => psa_w_hi_c_empty_n,
        psa_w_hi_read => fft_to_psa_U0_psa_w_hi_read,
        m_axis_result_TDATA => fft_to_psa_U0_m_axis_result_TDATA,
        m_axis_result_TVALID => fft_to_psa_U0_m_axis_result_TVALID,
        m_axis_result_TREADY => m_axis_result_TREADY,
        m_axis_result_TKEEP => fft_to_psa_U0_m_axis_result_TKEEP,
        m_axis_result_TSTRB => fft_to_psa_U0_m_axis_result_TSTRB,
        m_axis_result_TUSER => fft_to_psa_U0_m_axis_result_TUSER,
        m_axis_result_TLAST => fft_to_psa_U0_m_axis_result_TLAST,
        m_axis_result_TID => fft_to_psa_U0_m_axis_result_TID,
        m_axis_result_TDEST => fft_to_psa_U0_m_axis_result_TDEST,
        tag_s19_dout => tag_s_dout,
        tag_s19_num_data_valid => tag_s_num_data_valid,
        tag_s19_fifo_cap => tag_s_fifo_cap,
        tag_s19_empty_n => tag_s_empty_n,
        tag_s19_read => fft_to_psa_U0_tag_s19_read);

    psa_l_lo_c_U : component fci_core_fifo_w10_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_psa_l_lo_c_din,
        if_full_n => psa_l_lo_c_full_n,
        if_write => entry_proc_U0_psa_l_lo_c_write,
        if_dout => psa_l_lo_c_dout,
        if_num_data_valid => psa_l_lo_c_num_data_valid,
        if_fifo_cap => psa_l_lo_c_fifo_cap,
        if_empty_n => psa_l_lo_c_empty_n,
        if_read => fft_to_psa_U0_psa_l_lo_read);

    psa_l_hi_c_U : component fci_core_fifo_w10_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_psa_l_hi_c_din,
        if_full_n => psa_l_hi_c_full_n,
        if_write => entry_proc_U0_psa_l_hi_c_write,
        if_dout => psa_l_hi_c_dout,
        if_num_data_valid => psa_l_hi_c_num_data_valid,
        if_fifo_cap => psa_l_hi_c_fifo_cap,
        if_empty_n => psa_l_hi_c_empty_n,
        if_read => fft_to_psa_U0_psa_l_hi_read);

    psa_w_lo_c_U : component fci_core_fifo_w10_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_psa_w_lo_c_din,
        if_full_n => psa_w_lo_c_full_n,
        if_write => entry_proc_U0_psa_w_lo_c_write,
        if_dout => psa_w_lo_c_dout,
        if_num_data_valid => psa_w_lo_c_num_data_valid,
        if_fifo_cap => psa_w_lo_c_fifo_cap,
        if_empty_n => psa_w_lo_c_empty_n,
        if_read => fft_to_psa_U0_psa_w_lo_read);

    psa_w_hi_c_U : component fci_core_fifo_w10_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_psa_w_hi_c_din,
        if_full_n => psa_w_hi_c_full_n,
        if_write => entry_proc_U0_psa_w_hi_c_write,
        if_dout => psa_w_hi_c_dout,
        if_num_data_valid => psa_w_hi_c_num_data_valid,
        if_fifo_cap => psa_w_hi_c_fifo_cap,
        if_empty_n => psa_w_hi_c_empty_n,
        if_read => fft_to_psa_U0_psa_w_hi_read);

    xn_s_U : component fci_core_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_fft_U0_xn_s_din,
        if_full_n => xn_s_full_n,
        if_write => axis_to_fft_U0_xn_s_write,
        if_dout => xn_s_dout,
        if_num_data_valid => xn_s_num_data_valid,
        if_fifo_cap => xn_s_fifo_cap,
        if_empty_n => xn_s_empty_n,
        if_read => fft_fci_fft_config_U0_xn_s_read);

    config_s_U : component fci_core_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_fft_U0_config_s18_din,
        if_full_n => config_s_full_n,
        if_write => axis_to_fft_U0_config_s18_write,
        if_dout => config_s_dout,
        if_num_data_valid => config_s_num_data_valid,
        if_fifo_cap => config_s_fifo_cap,
        if_empty_n => config_s_empty_n,
        if_read => fft_fci_fft_config_U0_config_s18_read);

    tag_s_U : component fci_core_fifo_w64_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_fft_U0_tag_s19_din,
        if_full_n => tag_s_full_n,
        if_write => axis_to_fft_U0_tag_s19_write,
        if_dout => tag_s_dout,
        if_num_data_valid => tag_s_num_data_valid,
        if_fifo_cap => tag_s_fifo_cap,
        if_empty_n => tag_s_empty_n,
        if_read => fft_to_psa_U0_tag_s19_read);

    xk_s_U : component fci_core_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_fci_fft_config_U0_xk_s_din,
        if_full_n => xk_s_full_n,
        if_write => fft_fci_fft_config_U0_xk_s_write,
        if_dout => xk_s_dout,
        if_num_data_valid => xk_s_num_data_valid,
        if_fifo_cap => xk_s_fifo_cap,
        if_empty_n => xk_s_empty_n,
        if_read => fft_to_psa_U0_xk_s_read);

    status_s_U : component fci_core_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_fci_fft_config_U0_status_s17_din,
        if_full_n => status_s_full_n,
        if_write => fft_fci_fft_config_U0_status_s17_write,
        if_dout => status_s_dout,
        if_num_data_valid => status_s_num_data_valid,
        if_fifo_cap => status_s_fifo_cap,
        if_empty_n => status_s_empty_n,
        if_read => fft_to_psa_U0_status_s17_read);

    start_for_fft_to_psa_U0_U : component fci_core_start_for_fft_to_psa_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_fft_to_psa_U0_din,
        if_full_n => start_for_fft_to_psa_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_fft_to_psa_U0_dout,
        if_empty_n => start_for_fft_to_psa_U0_empty_n,
        if_read => fft_to_psa_U0_ap_ready);

    start_for_fft_fci_fft_config_U0_U : component fci_core_start_for_fft_fci_fft_config_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_fft_fci_fft_config_U0_din,
        if_full_n => start_for_fft_fci_fft_config_U0_full_n,
        if_write => axis_to_fft_U0_start_write,
        if_dout => start_for_fft_fci_fft_config_U0_dout,
        if_empty_n => start_for_fft_fci_fft_config_U0_empty_n,
        if_read => fft_fci_fft_config_U0_ap_ready);





    ap_sync_reg_axis_to_fft_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_axis_to_fft_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_axis_to_fft_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_axis_to_fft_U0_ap_ready <= ap_sync_axis_to_fft_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= fft_to_psa_U0_ap_done;
    ap_idle <= (fft_to_psa_U0_ap_idle and fft_fci_fft_config_U0_ap_idle and entry_proc_U0_ap_idle and axis_to_fft_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_axis_to_fft_U0_ap_ready <= (axis_to_fft_U0_ap_ready or ap_sync_reg_axis_to_fft_U0_ap_ready);
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_ready <= (ap_sync_entry_proc_U0_ap_ready and ap_sync_axis_to_fft_U0_ap_ready);
    axis_to_fft_U0_ap_continue <= ap_const_logic_1;
    axis_to_fft_U0_ap_start <= ((ap_sync_reg_axis_to_fft_U0_ap_ready xor ap_const_logic_1) and ap_start);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    fft_fci_fft_config_U0_ap_continue <= ap_const_logic_1;
    fft_fci_fft_config_U0_ap_start <= start_for_fft_fci_fft_config_U0_empty_n;
    fft_to_psa_U0_ap_continue <= ap_const_logic_1;
    fft_to_psa_U0_ap_start <= start_for_fft_to_psa_U0_empty_n;
    m_axis_result_TDATA <= fft_to_psa_U0_m_axis_result_TDATA;
    m_axis_result_TDEST <= fft_to_psa_U0_m_axis_result_TDEST;
    m_axis_result_TID <= fft_to_psa_U0_m_axis_result_TID;
    m_axis_result_TKEEP <= fft_to_psa_U0_m_axis_result_TKEEP;
    m_axis_result_TLAST <= fft_to_psa_U0_m_axis_result_TLAST;
    m_axis_result_TSTRB <= fft_to_psa_U0_m_axis_result_TSTRB;
    m_axis_result_TUSER <= fft_to_psa_U0_m_axis_result_TUSER;
    m_axis_result_TVALID <= fft_to_psa_U0_m_axis_result_TVALID;
    s_axis_data_TREADY <= axis_to_fft_U0_s_axis_data_TREADY;
    start_for_fft_fci_fft_config_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_fft_to_psa_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
