-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fci_core_fft_fci_fft_config_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    xn_s_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    xn_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    xn_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    xn_s_empty_n : IN STD_LOGIC;
    xn_s_read : OUT STD_LOGIC;
    xk_s_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    xk_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    xk_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    xk_s_full_n : IN STD_LOGIC;
    xk_s_write : OUT STD_LOGIC;
    status_s17_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    status_s17_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    status_s17_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    status_s17_full_n : IN STD_LOGIC;
    status_s17_write : OUT STD_LOGIC;
    config_s18_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    config_s18_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    config_s18_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    config_s18_empty_n : IN STD_LOGIC;
    config_s18_read : OUT STD_LOGIC );
end;


architecture behav of fci_core_fft_fci_fft_config_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fft_syn_fci_fft_config_s_fu_20_ap_ce : STD_LOGIC;
    signal grp_fft_syn_fci_fft_config_s_fu_20_ap_start : STD_LOGIC;
    signal grp_fft_syn_fci_fft_config_s_fu_20_ap_done : STD_LOGIC;
    signal grp_fft_syn_fci_fft_config_s_fu_20_ap_idle : STD_LOGIC;
    signal grp_fft_syn_fci_fft_config_s_fu_20_ap_ready : STD_LOGIC;
    signal grp_fft_syn_fci_fft_config_s_fu_20_xn_read : STD_LOGIC;
    signal grp_fft_syn_fci_fft_config_s_fu_20_xk_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft_syn_fci_fft_config_s_fu_20_xk_write : STD_LOGIC;
    signal grp_fft_syn_fci_fft_config_s_fu_20_status_data_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fft_syn_fci_fft_config_s_fu_20_status_data_V_write : STD_LOGIC;
    signal grp_fft_syn_fci_fft_config_s_fu_20_config_ch_data_V_read : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state1_ignore_call4 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fft_syn_fci_fft_config_s_fu_20_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fci_core_fft_syn_fci_fft_config_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        xn_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        xn_empty_n : IN STD_LOGIC;
        xn_read : OUT STD_LOGIC;
        xk_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xk_full_n : IN STD_LOGIC;
        xk_write : OUT STD_LOGIC;
        status_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_data_V_full_n : IN STD_LOGIC;
        status_data_V_write : OUT STD_LOGIC;
        config_ch_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        config_ch_data_V_empty_n : IN STD_LOGIC;
        config_ch_data_V_read : OUT STD_LOGIC );
    end component;



begin
    grp_fft_syn_fci_fft_config_s_fu_20 : component fci_core_fft_syn_fci_fft_config_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_ce => grp_fft_syn_fci_fft_config_s_fu_20_ap_ce,
        ap_start => grp_fft_syn_fci_fft_config_s_fu_20_ap_start,
        ap_done => grp_fft_syn_fci_fft_config_s_fu_20_ap_done,
        ap_idle => grp_fft_syn_fci_fft_config_s_fu_20_ap_idle,
        ap_ready => grp_fft_syn_fci_fft_config_s_fu_20_ap_ready,
        xn_dout => xn_s_dout,
        xn_empty_n => xn_s_empty_n,
        xn_read => grp_fft_syn_fci_fft_config_s_fu_20_xn_read,
        xk_din => grp_fft_syn_fci_fft_config_s_fu_20_xk_din,
        xk_full_n => xk_s_full_n,
        xk_write => grp_fft_syn_fci_fft_config_s_fu_20_xk_write,
        status_data_V_din => grp_fft_syn_fci_fft_config_s_fu_20_status_data_V_din,
        status_data_V_full_n => status_s17_full_n,
        status_data_V_write => grp_fft_syn_fci_fft_config_s_fu_20_status_data_V_write,
        config_ch_data_V_dout => config_s18_dout,
        config_ch_data_V_empty_n => config_s18_empty_n,
        config_ch_data_V_read => grp_fft_syn_fci_fft_config_s_fu_20_config_ch_data_V_read);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_fft_syn_fci_fft_config_s_fu_20_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_fft_syn_fci_fft_config_s_fu_20_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft_syn_fci_fft_config_s_fu_20_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_fft_syn_fci_fft_config_s_fu_20_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft_syn_fci_fft_config_s_fu_20_ap_ready = ap_const_logic_1)) then 
                    grp_fft_syn_fci_fft_config_s_fu_20_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_fft_syn_fci_fft_config_s_fu_20_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_fft_syn_fci_fft_config_s_fu_20_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_fft_syn_fci_fft_config_s_fu_20_ap_done)
    begin
        if ((grp_fft_syn_fci_fft_config_s_fu_20_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call4_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call4 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_fft_syn_fci_fft_config_s_fu_20_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_fft_syn_fci_fft_config_s_fu_20_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_fft_syn_fci_fft_config_s_fu_20_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_fft_syn_fci_fft_config_s_fu_20_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    config_s18_read_assign_proc : process(ap_CS_fsm_state1, grp_fft_syn_fci_fft_config_s_fu_20_config_ch_data_V_read, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            config_s18_read <= grp_fft_syn_fci_fft_config_s_fu_20_config_ch_data_V_read;
        else 
            config_s18_read <= ap_const_logic_0;
        end if; 
    end process;


    grp_fft_syn_fci_fft_config_s_fu_20_ap_ce_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fft_syn_fci_fft_config_s_fu_20_ap_ce <= ap_const_logic_1;
        else 
            grp_fft_syn_fci_fft_config_s_fu_20_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fft_syn_fci_fft_config_s_fu_20_ap_start <= grp_fft_syn_fci_fft_config_s_fu_20_ap_start_reg;
    status_s17_din <= grp_fft_syn_fci_fft_config_s_fu_20_status_data_V_din;

    status_s17_write_assign_proc : process(ap_CS_fsm_state1, grp_fft_syn_fci_fft_config_s_fu_20_status_data_V_write, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            status_s17_write <= grp_fft_syn_fci_fft_config_s_fu_20_status_data_V_write;
        else 
            status_s17_write <= ap_const_logic_0;
        end if; 
    end process;

    xk_s_din <= grp_fft_syn_fci_fft_config_s_fu_20_xk_din;

    xk_s_write_assign_proc : process(ap_CS_fsm_state1, grp_fft_syn_fci_fft_config_s_fu_20_xk_write, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xk_s_write <= grp_fft_syn_fci_fft_config_s_fu_20_xk_write;
        else 
            xk_s_write <= ap_const_logic_0;
        end if; 
    end process;


    xn_s_read_assign_proc : process(ap_CS_fsm_state1, grp_fft_syn_fci_fft_config_s_fu_20_xn_read, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xn_s_read <= grp_fft_syn_fci_fft_config_s_fu_20_xn_read;
        else 
            xn_s_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
