-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fci_core is
port (
    s_axis_data_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    s_axis_data_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    s_axis_data_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    s_axis_data_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_data_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_data_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_data_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_result_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_result_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_result_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_result_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_result_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_result_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_result_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    psa_l_lo_s_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    psa_l_lo_s_empty_n : IN STD_LOGIC;
    psa_l_lo_s_read : OUT STD_LOGIC;
    psa_l_hi_s_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    psa_l_hi_s_empty_n : IN STD_LOGIC;
    psa_l_hi_s_read : OUT STD_LOGIC;
    psa_w_lo_s_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    psa_w_lo_s_empty_n : IN STD_LOGIC;
    psa_w_lo_s_read : OUT STD_LOGIC;
    psa_w_hi_s_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    psa_w_hi_s_empty_n : IN STD_LOGIC;
    psa_w_hi_s_read : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_data_TVALID : IN STD_LOGIC;
    s_axis_data_TREADY : OUT STD_LOGIC;
    m_axis_result_TVALID : OUT STD_LOGIC;
    m_axis_result_TREADY : IN STD_LOGIC );
end;


architecture behav of fci_core is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fci_core_fci_core,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.600000,HLS_SYN_LAT=3200,HLS_SYN_TPT=3197,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=10440,HLS_SYN_LUT=8862,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal axis_to_fft_U0_ap_start : STD_LOGIC;
    signal axis_to_fft_U0_ap_done : STD_LOGIC;
    signal axis_to_fft_U0_ap_continue : STD_LOGIC;
    signal axis_to_fft_U0_ap_idle : STD_LOGIC;
    signal axis_to_fft_U0_ap_ready : STD_LOGIC;
    signal axis_to_fft_U0_start_out : STD_LOGIC;
    signal axis_to_fft_U0_start_write : STD_LOGIC;
    signal axis_to_fft_U0_s_axis_data_TREADY : STD_LOGIC;
    signal axis_to_fft_U0_xn_s_din : STD_LOGIC_VECTOR (31 downto 0);
    signal axis_to_fft_U0_xn_s_write : STD_LOGIC;
    signal axis_to_fft_U0_config_s5_din : STD_LOGIC_VECTOR (7 downto 0);
    signal axis_to_fft_U0_config_s5_write : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_start : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_done : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_continue : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_idle : STD_LOGIC;
    signal fft_fci_fft_config_U0_ap_ready : STD_LOGIC;
    signal fft_fci_fft_config_U0_start_out : STD_LOGIC;
    signal fft_fci_fft_config_U0_start_write : STD_LOGIC;
    signal fft_fci_fft_config_U0_xn_s_read : STD_LOGIC;
    signal fft_fci_fft_config_U0_xk_s_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_fci_fft_config_U0_xk_s_write : STD_LOGIC;
    signal fft_fci_fft_config_U0_status_s4_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_fci_fft_config_U0_status_s4_write : STD_LOGIC;
    signal fft_fci_fft_config_U0_config_s5_read : STD_LOGIC;
    signal fft_to_psa_U0_ap_start : STD_LOGIC;
    signal fft_to_psa_U0_ap_done : STD_LOGIC;
    signal fft_to_psa_U0_ap_continue : STD_LOGIC;
    signal fft_to_psa_U0_ap_idle : STD_LOGIC;
    signal fft_to_psa_U0_ap_ready : STD_LOGIC;
    signal fft_to_psa_U0_xk_s_read : STD_LOGIC;
    signal fft_to_psa_U0_status_s4_read : STD_LOGIC;
    signal fft_to_psa_U0_psa_l_lo_s_read : STD_LOGIC;
    signal fft_to_psa_U0_psa_l_hi_s_read : STD_LOGIC;
    signal fft_to_psa_U0_psa_w_lo_s_read : STD_LOGIC;
    signal fft_to_psa_U0_psa_w_hi_s_read : STD_LOGIC;
    signal fft_to_psa_U0_m_axis_result_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_to_psa_U0_m_axis_result_TVALID : STD_LOGIC;
    signal fft_to_psa_U0_m_axis_result_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal fft_to_psa_U0_m_axis_result_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal fft_to_psa_U0_m_axis_result_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal fft_to_psa_U0_m_axis_result_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal fft_to_psa_U0_m_axis_result_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal fft_to_psa_U0_m_axis_result_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal xn_s_full_n : STD_LOGIC;
    signal xn_s_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal xn_s_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal xn_s_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal xn_s_empty_n : STD_LOGIC;
    signal config_s_full_n : STD_LOGIC;
    signal config_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal config_s_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal config_s_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal config_s_empty_n : STD_LOGIC;
    signal xk_s_full_n : STD_LOGIC;
    signal xk_s_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal xk_s_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal xk_s_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal xk_s_empty_n : STD_LOGIC;
    signal status_s_full_n : STD_LOGIC;
    signal status_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal status_s_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal status_s_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal status_s_empty_n : STD_LOGIC;
    signal start_for_fft_fci_fft_config_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_fci_fft_config_U0_full_n : STD_LOGIC;
    signal start_for_fft_fci_fft_config_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_fci_fft_config_U0_empty_n : STD_LOGIC;
    signal start_for_fft_to_psa_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_to_psa_U0_full_n : STD_LOGIC;
    signal start_for_fft_to_psa_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_to_psa_U0_empty_n : STD_LOGIC;

    component fci_core_axis_to_fft IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        s_axis_data_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        s_axis_data_TVALID : IN STD_LOGIC;
        s_axis_data_TREADY : OUT STD_LOGIC;
        s_axis_data_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
        s_axis_data_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
        s_axis_data_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_data_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_data_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_data_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        xn_s_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xn_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        xn_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        xn_s_full_n : IN STD_LOGIC;
        xn_s_write : OUT STD_LOGIC;
        config_s5_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        config_s5_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        config_s5_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        config_s5_full_n : IN STD_LOGIC;
        config_s5_write : OUT STD_LOGIC );
    end component;


    component fci_core_fft_fci_fft_config_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        xn_s_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        xn_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        xn_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        xn_s_empty_n : IN STD_LOGIC;
        xn_s_read : OUT STD_LOGIC;
        xk_s_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xk_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        xk_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        xk_s_full_n : IN STD_LOGIC;
        xk_s_write : OUT STD_LOGIC;
        status_s4_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_s4_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        status_s4_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        status_s4_full_n : IN STD_LOGIC;
        status_s4_write : OUT STD_LOGIC;
        config_s5_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        config_s5_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        config_s5_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        config_s5_empty_n : IN STD_LOGIC;
        config_s5_read : OUT STD_LOGIC );
    end component;


    component fci_core_fft_to_psa IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        xk_s_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        xk_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        xk_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        xk_s_empty_n : IN STD_LOGIC;
        xk_s_read : OUT STD_LOGIC;
        status_s4_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        status_s4_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        status_s4_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        status_s4_empty_n : IN STD_LOGIC;
        status_s4_read : OUT STD_LOGIC;
        psa_l_lo_s_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_l_lo_s_empty_n : IN STD_LOGIC;
        psa_l_lo_s_read : OUT STD_LOGIC;
        psa_l_hi_s_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_l_hi_s_empty_n : IN STD_LOGIC;
        psa_l_hi_s_read : OUT STD_LOGIC;
        psa_w_lo_s_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_w_lo_s_empty_n : IN STD_LOGIC;
        psa_w_lo_s_read : OUT STD_LOGIC;
        psa_w_hi_s_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        psa_w_hi_s_empty_n : IN STD_LOGIC;
        psa_w_hi_s_read : OUT STD_LOGIC;
        m_axis_result_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axis_result_TVALID : OUT STD_LOGIC;
        m_axis_result_TREADY : IN STD_LOGIC;
        m_axis_result_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_result_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_result_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_result_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_result_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_result_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fci_core_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fci_core_fifo_w8_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fci_core_start_for_fft_fci_fft_config_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fci_core_start_for_fft_to_psa_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    axis_to_fft_U0 : component fci_core_axis_to_fft
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => axis_to_fft_U0_ap_start,
        start_full_n => start_for_fft_fci_fft_config_U0_full_n,
        ap_done => axis_to_fft_U0_ap_done,
        ap_continue => axis_to_fft_U0_ap_continue,
        ap_idle => axis_to_fft_U0_ap_idle,
        ap_ready => axis_to_fft_U0_ap_ready,
        start_out => axis_to_fft_U0_start_out,
        start_write => axis_to_fft_U0_start_write,
        s_axis_data_TDATA => s_axis_data_TDATA,
        s_axis_data_TVALID => s_axis_data_TVALID,
        s_axis_data_TREADY => axis_to_fft_U0_s_axis_data_TREADY,
        s_axis_data_TKEEP => s_axis_data_TKEEP,
        s_axis_data_TSTRB => s_axis_data_TSTRB,
        s_axis_data_TUSER => s_axis_data_TUSER,
        s_axis_data_TLAST => s_axis_data_TLAST,
        s_axis_data_TID => s_axis_data_TID,
        s_axis_data_TDEST => s_axis_data_TDEST,
        xn_s_din => axis_to_fft_U0_xn_s_din,
        xn_s_num_data_valid => xn_s_num_data_valid,
        xn_s_fifo_cap => xn_s_fifo_cap,
        xn_s_full_n => xn_s_full_n,
        xn_s_write => axis_to_fft_U0_xn_s_write,
        config_s5_din => axis_to_fft_U0_config_s5_din,
        config_s5_num_data_valid => config_s_num_data_valid,
        config_s5_fifo_cap => config_s_fifo_cap,
        config_s5_full_n => config_s_full_n,
        config_s5_write => axis_to_fft_U0_config_s5_write);

    fft_fci_fft_config_U0 : component fci_core_fft_fci_fft_config_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => fft_fci_fft_config_U0_ap_start,
        start_full_n => start_for_fft_to_psa_U0_full_n,
        ap_done => fft_fci_fft_config_U0_ap_done,
        ap_continue => fft_fci_fft_config_U0_ap_continue,
        ap_idle => fft_fci_fft_config_U0_ap_idle,
        ap_ready => fft_fci_fft_config_U0_ap_ready,
        start_out => fft_fci_fft_config_U0_start_out,
        start_write => fft_fci_fft_config_U0_start_write,
        xn_s_dout => xn_s_dout,
        xn_s_num_data_valid => xn_s_num_data_valid,
        xn_s_fifo_cap => xn_s_fifo_cap,
        xn_s_empty_n => xn_s_empty_n,
        xn_s_read => fft_fci_fft_config_U0_xn_s_read,
        xk_s_din => fft_fci_fft_config_U0_xk_s_din,
        xk_s_num_data_valid => xk_s_num_data_valid,
        xk_s_fifo_cap => xk_s_fifo_cap,
        xk_s_full_n => xk_s_full_n,
        xk_s_write => fft_fci_fft_config_U0_xk_s_write,
        status_s4_din => fft_fci_fft_config_U0_status_s4_din,
        status_s4_num_data_valid => status_s_num_data_valid,
        status_s4_fifo_cap => status_s_fifo_cap,
        status_s4_full_n => status_s_full_n,
        status_s4_write => fft_fci_fft_config_U0_status_s4_write,
        config_s5_dout => config_s_dout,
        config_s5_num_data_valid => config_s_num_data_valid,
        config_s5_fifo_cap => config_s_fifo_cap,
        config_s5_empty_n => config_s_empty_n,
        config_s5_read => fft_fci_fft_config_U0_config_s5_read);

    fft_to_psa_U0 : component fci_core_fft_to_psa
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => fft_to_psa_U0_ap_start,
        ap_done => fft_to_psa_U0_ap_done,
        ap_continue => fft_to_psa_U0_ap_continue,
        ap_idle => fft_to_psa_U0_ap_idle,
        ap_ready => fft_to_psa_U0_ap_ready,
        xk_s_dout => xk_s_dout,
        xk_s_num_data_valid => xk_s_num_data_valid,
        xk_s_fifo_cap => xk_s_fifo_cap,
        xk_s_empty_n => xk_s_empty_n,
        xk_s_read => fft_to_psa_U0_xk_s_read,
        status_s4_dout => status_s_dout,
        status_s4_num_data_valid => status_s_num_data_valid,
        status_s4_fifo_cap => status_s_fifo_cap,
        status_s4_empty_n => status_s_empty_n,
        status_s4_read => fft_to_psa_U0_status_s4_read,
        psa_l_lo_s_dout => psa_l_lo_s_dout,
        psa_l_lo_s_empty_n => psa_l_lo_s_empty_n,
        psa_l_lo_s_read => fft_to_psa_U0_psa_l_lo_s_read,
        psa_l_hi_s_dout => psa_l_hi_s_dout,
        psa_l_hi_s_empty_n => psa_l_hi_s_empty_n,
        psa_l_hi_s_read => fft_to_psa_U0_psa_l_hi_s_read,
        psa_w_lo_s_dout => psa_w_lo_s_dout,
        psa_w_lo_s_empty_n => psa_w_lo_s_empty_n,
        psa_w_lo_s_read => fft_to_psa_U0_psa_w_lo_s_read,
        psa_w_hi_s_dout => psa_w_hi_s_dout,
        psa_w_hi_s_empty_n => psa_w_hi_s_empty_n,
        psa_w_hi_s_read => fft_to_psa_U0_psa_w_hi_s_read,
        m_axis_result_TDATA => fft_to_psa_U0_m_axis_result_TDATA,
        m_axis_result_TVALID => fft_to_psa_U0_m_axis_result_TVALID,
        m_axis_result_TREADY => m_axis_result_TREADY,
        m_axis_result_TKEEP => fft_to_psa_U0_m_axis_result_TKEEP,
        m_axis_result_TSTRB => fft_to_psa_U0_m_axis_result_TSTRB,
        m_axis_result_TUSER => fft_to_psa_U0_m_axis_result_TUSER,
        m_axis_result_TLAST => fft_to_psa_U0_m_axis_result_TLAST,
        m_axis_result_TID => fft_to_psa_U0_m_axis_result_TID,
        m_axis_result_TDEST => fft_to_psa_U0_m_axis_result_TDEST);

    xn_s_U : component fci_core_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_fft_U0_xn_s_din,
        if_full_n => xn_s_full_n,
        if_write => axis_to_fft_U0_xn_s_write,
        if_dout => xn_s_dout,
        if_num_data_valid => xn_s_num_data_valid,
        if_fifo_cap => xn_s_fifo_cap,
        if_empty_n => xn_s_empty_n,
        if_read => fft_fci_fft_config_U0_xn_s_read);

    config_s_U : component fci_core_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_fft_U0_config_s5_din,
        if_full_n => config_s_full_n,
        if_write => axis_to_fft_U0_config_s5_write,
        if_dout => config_s_dout,
        if_num_data_valid => config_s_num_data_valid,
        if_fifo_cap => config_s_fifo_cap,
        if_empty_n => config_s_empty_n,
        if_read => fft_fci_fft_config_U0_config_s5_read);

    xk_s_U : component fci_core_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_fci_fft_config_U0_xk_s_din,
        if_full_n => xk_s_full_n,
        if_write => fft_fci_fft_config_U0_xk_s_write,
        if_dout => xk_s_dout,
        if_num_data_valid => xk_s_num_data_valid,
        if_fifo_cap => xk_s_fifo_cap,
        if_empty_n => xk_s_empty_n,
        if_read => fft_to_psa_U0_xk_s_read);

    status_s_U : component fci_core_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_fci_fft_config_U0_status_s4_din,
        if_full_n => status_s_full_n,
        if_write => fft_fci_fft_config_U0_status_s4_write,
        if_dout => status_s_dout,
        if_num_data_valid => status_s_num_data_valid,
        if_fifo_cap => status_s_fifo_cap,
        if_empty_n => status_s_empty_n,
        if_read => fft_to_psa_U0_status_s4_read);

    start_for_fft_fci_fft_config_U0_U : component fci_core_start_for_fft_fci_fft_config_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_fft_fci_fft_config_U0_din,
        if_full_n => start_for_fft_fci_fft_config_U0_full_n,
        if_write => axis_to_fft_U0_start_write,
        if_dout => start_for_fft_fci_fft_config_U0_dout,
        if_empty_n => start_for_fft_fci_fft_config_U0_empty_n,
        if_read => fft_fci_fft_config_U0_ap_ready);

    start_for_fft_to_psa_U0_U : component fci_core_start_for_fft_to_psa_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_fft_to_psa_U0_din,
        if_full_n => start_for_fft_to_psa_U0_full_n,
        if_write => fft_fci_fft_config_U0_start_write,
        if_dout => start_for_fft_to_psa_U0_dout,
        if_empty_n => start_for_fft_to_psa_U0_empty_n,
        if_read => fft_to_psa_U0_ap_ready);





    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    axis_to_fft_U0_ap_continue <= ap_const_logic_1;
    axis_to_fft_U0_ap_start <= ap_const_logic_1;
    fft_fci_fft_config_U0_ap_continue <= ap_const_logic_1;
    fft_fci_fft_config_U0_ap_start <= start_for_fft_fci_fft_config_U0_empty_n;
    fft_to_psa_U0_ap_continue <= ap_const_logic_1;
    fft_to_psa_U0_ap_start <= start_for_fft_to_psa_U0_empty_n;
    m_axis_result_TDATA <= fft_to_psa_U0_m_axis_result_TDATA;
    m_axis_result_TDEST <= fft_to_psa_U0_m_axis_result_TDEST;
    m_axis_result_TID <= fft_to_psa_U0_m_axis_result_TID;
    m_axis_result_TKEEP <= fft_to_psa_U0_m_axis_result_TKEEP;
    m_axis_result_TLAST <= fft_to_psa_U0_m_axis_result_TLAST;
    m_axis_result_TSTRB <= fft_to_psa_U0_m_axis_result_TSTRB;
    m_axis_result_TUSER <= fft_to_psa_U0_m_axis_result_TUSER;
    m_axis_result_TVALID <= fft_to_psa_U0_m_axis_result_TVALID;
    psa_l_hi_s_read <= fft_to_psa_U0_psa_l_hi_s_read;
    psa_l_lo_s_read <= fft_to_psa_U0_psa_l_lo_s_read;
    psa_w_hi_s_read <= fft_to_psa_U0_psa_w_hi_s_read;
    psa_w_lo_s_read <= fft_to_psa_U0_psa_w_lo_s_read;
    s_axis_data_TREADY <= axis_to_fft_U0_s_axis_data_TREADY;
    start_for_fft_fci_fft_config_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_fft_to_psa_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
