-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fci_core_fft_to_psa_Pipeline_BIN_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    xk_s_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    xk_s_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    xk_s_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    xk_s_empty_n : IN STD_LOGIC;
    xk_s_read : OUT STD_LOGIC;
    psa_l_lo_V_cast : IN STD_LOGIC_VECTOR (9 downto 0);
    psa_l_hi_V_cast : IN STD_LOGIC_VECTOR (9 downto 0);
    psa_w_lo_V_cast : IN STD_LOGIC_VECTOR (9 downto 0);
    zext_ln59 : IN STD_LOGIC_VECTOR (9 downto 0);
    psa_w_V_out : OUT STD_LOGIC_VECTOR (27 downto 0);
    psa_w_V_out_ap_vld : OUT STD_LOGIC;
    psa_l_V_out : OUT STD_LOGIC_VECTOR (27 downto 0);
    psa_l_V_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fci_core_fft_to_psa_Pipeline_BIN_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln59_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal xk_s_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln1031_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1031_reg_401 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln1039_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_406 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1031_1_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1031_1_reg_411 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_1_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_1_reg_416 : STD_LOGIC_VECTOR (0 downto 0);
    signal psa_l_V_fu_68 : STD_LOGIC_VECTOR (27 downto 0);
    signal psa_l_V_2_fu_319_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal psa_w_V_fu_72 : STD_LOGIC_VECTOR (27 downto 0);
    signal psa_w_V_2_fu_349_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal k_1_fu_76 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_2_fu_164_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_k : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal psa_l_lo_V_cast_cast_fu_136_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal psa_l_hi_V_cast_cast_fu_132_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal psa_w_lo_V_cast_cast_fu_128_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln59_cast_fu_124_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal xk_M_real_fu_205_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln813_fu_219_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_223_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal wide_V_1_fu_231_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln7_fu_237_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal xk_M_imag_fu_209_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln813_1_fu_253_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_1_fu_257_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal wide_V_3_fu_265_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln7_1_fu_271_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln838_1_fu_279_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln_fu_245_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal xor_ln1031_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1039_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal asdm_fu_287_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln813_fu_309_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln63_fu_303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal psa_l_V_1_fu_313_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal xor_ln1031_1_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1039_1_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln65_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal psa_w_V_1_fu_343_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fci_core_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fci_core_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    k_1_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln59_fu_158_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_1_fu_76 <= k_2_fu_164_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_1_fu_76 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    psa_l_V_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    psa_l_V_fu_68 <= ap_const_lv28_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    psa_l_V_fu_68 <= psa_l_V_2_fu_319_p3;
                end if;
            end if; 
        end if;
    end process;

    psa_w_V_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    psa_w_V_fu_72 <= ap_const_lv28_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    psa_w_V_fu_72 <= psa_w_V_2_fu_349_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln59_fu_158_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1031_1_reg_411 <= icmp_ln1031_1_fu_182_p2;
                icmp_ln1031_reg_401 <= icmp_ln1031_fu_170_p2;
                icmp_ln1039_1_reg_416 <= icmp_ln1039_1_fu_188_p2;
                icmp_ln1039_reg_406 <= icmp_ln1039_fu_176_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln63_fu_303_p2 <= (xor_ln1039_fu_298_p2 and xor_ln1031_fu_293_p2);
    and_ln65_fu_337_p2 <= (xor_ln1039_1_fu_332_p2 and xor_ln1031_1_fu_327_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, xk_s_empty_n)
    begin
                ap_block_pp0_stage0_01001 <= ((xk_s_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, xk_s_empty_n)
    begin
                ap_block_pp0_stage0_11001 <= ((xk_s_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, xk_s_empty_n)
    begin
                ap_block_pp0_stage0_subdone <= ((xk_s_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(xk_s_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (xk_s_empty_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln59_fu_158_p2)
    begin
        if (((icmp_ln59_fu_158_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_1_fu_76)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_k <= k_1_fu_76;
        end if; 
    end process;

    asdm_fu_287_p2 <= std_logic_vector(unsigned(shl_ln838_1_fu_279_p3) + unsigned(shl_ln_fu_245_p3));
    icmp_ln1031_1_fu_182_p2 <= "1" when (unsigned(ap_sig_allocacmp_k) < unsigned(psa_w_lo_V_cast_cast_fu_128_p1)) else "0";
    icmp_ln1031_fu_170_p2 <= "1" when (unsigned(ap_sig_allocacmp_k) < unsigned(psa_l_lo_V_cast_cast_fu_136_p1)) else "0";
    icmp_ln1039_1_fu_188_p2 <= "1" when (unsigned(zext_ln59_cast_fu_124_p1) < unsigned(ap_sig_allocacmp_k)) else "0";
    icmp_ln1039_fu_176_p2 <= "1" when (unsigned(psa_l_hi_V_cast_cast_fu_132_p1) < unsigned(ap_sig_allocacmp_k)) else "0";
    icmp_ln59_fu_158_p2 <= "1" when (ap_sig_allocacmp_k = ap_const_lv11_400) else "0";
    k_2_fu_164_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k) + unsigned(ap_const_lv11_1));
    psa_l_V_1_fu_313_p2 <= std_logic_vector(unsigned(psa_l_V_fu_68) + unsigned(zext_ln813_fu_309_p1));
    psa_l_V_2_fu_319_p3 <= 
        psa_l_V_1_fu_313_p2 when (and_ln63_fu_303_p2(0) = '1') else 
        psa_l_V_fu_68;
    psa_l_V_out <= psa_l_V_fu_68;

    psa_l_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln59_fu_158_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln59_fu_158_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            psa_l_V_out_ap_vld <= ap_const_logic_1;
        else 
            psa_l_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    psa_l_hi_V_cast_cast_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(psa_l_hi_V_cast),11));
    psa_l_lo_V_cast_cast_fu_136_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(psa_l_lo_V_cast),11));
    psa_w_V_1_fu_343_p2 <= std_logic_vector(unsigned(psa_w_V_fu_72) + unsigned(zext_ln813_fu_309_p1));
    psa_w_V_2_fu_349_p3 <= 
        psa_w_V_1_fu_343_p2 when (and_ln65_fu_337_p2(0) = '1') else 
        psa_w_V_fu_72;
    psa_w_V_out <= psa_w_V_fu_72;

    psa_w_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln59_fu_158_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln59_fu_158_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            psa_w_V_out_ap_vld <= ap_const_logic_1;
        else 
            psa_w_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    psa_w_lo_V_cast_cast_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(psa_w_lo_V_cast),11));
    select_ln7_1_fu_271_p3 <= 
        wide_V_3_fu_265_p2 when (tmp_1_fu_257_p3(0) = '1') else 
        sext_ln813_1_fu_253_p1;
    select_ln7_fu_237_p3 <= 
        wide_V_1_fu_231_p2 when (tmp_fu_223_p3(0) = '1') else 
        sext_ln813_fu_219_p1;
        sext_ln813_1_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(xk_M_imag_fu_209_p4),17));

        sext_ln813_fu_219_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(xk_M_real_fu_205_p1),17));

    shl_ln838_1_fu_279_p3 <= (select_ln7_1_fu_271_p3 & ap_const_lv1_0);
    shl_ln_fu_245_p3 <= (select_ln7_fu_237_p3 & ap_const_lv1_0);
    tmp_1_fu_257_p3 <= xk_s_dout(31 downto 31);
    tmp_fu_223_p3 <= xk_s_dout(15 downto 15);
    wide_V_1_fu_231_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln813_fu_219_p1));
    wide_V_3_fu_265_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln813_1_fu_253_p1));
    xk_M_imag_fu_209_p4 <= xk_s_dout(31 downto 16);
    xk_M_real_fu_205_p1 <= xk_s_dout(16 - 1 downto 0);

    xk_s_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, xk_s_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xk_s_blk_n <= xk_s_empty_n;
        else 
            xk_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    xk_s_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            xk_s_read <= ap_const_logic_1;
        else 
            xk_s_read <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln1031_1_fu_327_p2 <= (icmp_ln1031_1_reg_411 xor ap_const_lv1_1);
    xor_ln1031_fu_293_p2 <= (icmp_ln1031_reg_401 xor ap_const_lv1_1);
    xor_ln1039_1_fu_332_p2 <= (icmp_ln1039_1_reg_416 xor ap_const_lv1_1);
    xor_ln1039_fu_298_p2 <= (icmp_ln1039_reg_406 xor ap_const_lv1_1);
    zext_ln59_cast_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln59),11));
    zext_ln813_fu_309_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(asdm_fu_287_p2),28));
end behav;
