# Vitis HLS 2022.2 batch script for fci_core.
# Usage: vitis_hls -f run_hls.tcl
#
# Runs C-simulation and C-synthesis against this project's actual target,
# the Digilent Cmod A7-35T (xc7a35tcpg236-1), clocked at 50 MHz to match the
# board's LTC2248 ADC sample rate. RTL/C-RTL cosimulation is a separate,
# slower step -- see run_cosim.tcl.

# This host's system gcc/binutils are much newer than the toolchain Vitis HLS 2022.2 bundles
# for csim; the bundled linker can't parse modern glibc's .relr.dyn sections. Force csim to use
# the system gcc instead (confirmed working when building csim.mk directly with this override).
set ::env(AP_GCC_PATH) /usr/bin

set script_dir [file dirname [file normalize [info script]]]
set core_dir   [file normalize "$script_dir/.."]
set repo_root  [file normalize "$script_dir/../../../.."]
set data_csv   "$repo_root/data/fci_verification_set.csv"

if {![file exists $data_csv]} {
    puts "ERROR: verification dataset not found at $data_csv"
    puts "Run: cd $repo_root/data && uv run prepare_dataset.py"
    exit 1
}

# Generated (gitignored) header instead of a -D command-line macro: cosim recompiles the
# testbench through its own separate build path, where a quoted string macro doesn't survive
# the tcl -> make -> shell -> gcc hop reliably (it does for plain csim, but not cosim -- see
# fci_core_tb.cpp for the full story). A real header sidesteps the quoting fragility entirely.
set header_fh [open "$core_dir/tb/data_csv_path.hpp" w]
puts $header_fh "// Auto-generated by run_hls.tcl -- do not edit, not committed (see .gitignore)."
puts $header_fh "static const char *const DATA_CSV_PATH = \"$data_csv\";"
close $header_fh

open_project -reset fci_core_prj
set_top fci_core

add_files "$core_dir/src/fci_core.cpp"
add_files -tb "$core_dir/tb/fci_core_tb.cpp" -cflags "-I$core_dir/src"

open_solution -reset "solution1"
set_part {xc7a35tcpg236-1}
create_clock -period 20 -name default

# csim_design's own build step can't link against this host's very new glibc (the toolchain
# Vitis HLS 2022.2 bundles predates .relr.dyn support). It still generates all the sources and
# a working Makefile before failing at the final link, so catch the failure here and rebuild/run
# with the system toolchain via scripts/build_and_run_csim.sh afterwards instead.
if {[catch {csim_design} result]} {
    puts "NOTE: vitis_hls's own csim build failed as expected on this host (bundled linker vs."
    puts "  this host's newer glibc) -- run scripts/build_and_run_csim.sh to actually build/run it."
    puts "  (tcl error was: $result)"
}

csynth_design

export_design -format ip_catalog -output "$repo_root/fpga/ip/fci_core.zip"

exit
