/*
 * registers.h
 *
 * Peripheral base addresses and register offsets for the FCI acquisition chain
 * (trigger_core -> fci_core -> axi_dma -> axi_bram_ctrl), plus the AXI IIC/UARTLITE/INTC
 * peripherals shared with the MicroBlaze subsystem.
 *
 * Base addresses are pulled from xparameters.h (regenerated by Vitis from the current hardware
 * platform) rather than hardcoded, so a block-design address-map change can't silently desync
 * this header from the actual bitstream. trigger_core is hand-written RTL with no generated
 * driver, so its register map is defined here by hand -- keep in sync with
 * fpga/rtl/trigger_core/src/axi4lite_regs.vhd if that map ever changes.
 */

#ifndef SRC_REGISTERS_H_
#define SRC_REGISTERS_H_

#include "xparameters.h"
#include "xaxidma_hw.h"    /* generated by Vitis; authoritative source for axi_dma's direct-
                            * register-mode (Simple DMA) offsets and status/control bit masks */
#include "xfci_core_hw.h" /* generated by Vitis HLS; authoritative source for fci_core's
                           * s_axi_control register offsets (see fci_core/drivers/fci_core_v1_0) */
#include "xintc_l.h"      /* generated by Vitis; authoritative source for axi_intc's register map */

/* ---------------------------------------------------------------------------------------------
 * trigger_core (fpga/rtl/trigger_core) -- hand-written AXI4-Lite register map
 * ------------------------------------------------------------------------------------------- */
#define TRIGGER_CORE_BASEADDR XPAR_TRIGGER_CORE_0_BASEADDR

#define TRIGGER_CORE_THRESHOLD_OFFSET 0x00 /* [13:0], offset-binary ADC code */
#define TRIGGER_CORE_POLARITY_OFFSET 0x04  /* [0]: 1 = rising crossing, 0 = falling crossing */
#define TRIGGER_CORE_DELAY_OFFSET 0x08     /* [8:0], hw-clamped to 2..256 */
#define TRIGGER_CORE_DEPTH_OFFSET 0x0C     /* [12:0], hw-clamped to 1..4096 */

#define TRIGGER_CORE_POLARITY_RISING 0x1
#define TRIGGER_CORE_POLARITY_FALLING 0x0

/* ---------------------------------------------------------------------------------------------
 * fci_core (fpga/hls/fci_core) -- Vitis HLS-generated s_axi_control map, offsets taken directly
 * from xfci_core_hw.h rather than retyped, so a future HLS re-synth/re-export can't desync them.
 * ------------------------------------------------------------------------------------------- */
#define FCI_CORE_BASEADDR XPAR_FCI_CORE_0_S_AXI_CONTROL_BASEADDR

#define FCI_CORE_AP_CTRL_OFFSET XFCI_CORE_CONTROL_ADDR_AP_CTRL /* bit0 ap_start, bit1 ap_done,
                                    * bit2 ap_idle, bit3 ap_ready, bit7 auto_restart, bit9 interrupt */
#define FCI_CORE_GIE_OFFSET XFCI_CORE_CONTROL_ADDR_GIE
#define FCI_CORE_IER_OFFSET XFCI_CORE_CONTROL_ADDR_IER
#define FCI_CORE_ISR_OFFSET XFCI_CORE_CONTROL_ADDR_ISR
#define FCI_CORE_PSA_L_LO_OFFSET XFCI_CORE_CONTROL_ADDR_PSA_L_LO_DATA
#define FCI_CORE_PSA_L_HI_OFFSET XFCI_CORE_CONTROL_ADDR_PSA_L_HI_DATA
#define FCI_CORE_PSA_W_LO_OFFSET XFCI_CORE_CONTROL_ADDR_PSA_W_LO_DATA
#define FCI_CORE_PSA_W_HI_OFFSET XFCI_CORE_CONTROL_ADDR_PSA_W_HI_DATA

#define FCI_CORE_AP_CTRL_START (1U << 0)
#define FCI_CORE_AP_CTRL_DONE (1U << 1)
#define FCI_CORE_AP_CTRL_IDLE (1U << 2)
#define FCI_CORE_AP_CTRL_READY (1U << 3)
#define FCI_CORE_AP_CTRL_AUTO_RESTART (1U << 7)
#define FCI_CORE_AP_CTRL_INTERRUPT (1U << 9)

/* ---------------------------------------------------------------------------------------------
 * axi_dma_0 (Simple DMA, no Scatter-Gather) -- S2MM path carries {PSA_l, PSA_w} per event into
 * axi_bram_ctrl_0; MM2S path reads it back to the MicroBlaze over S0_AXIS for fast readback.
 * ------------------------------------------------------------------------------------------- */
#define AXI_DMA_BASEADDR XPAR_AXI_DMA_0_BASEADDR
#define AXI_DMA_DEVICE_ID XPAR_AXI_DMA_0_DEVICE_ID

/* c_include_sg=0 (Simple DMA): direct-register mode only, channel-relative offsets from
 * xaxidma_hw.h (XAXIDMA_TX_OFFSET/XAXIDMA_RX_OFFSET = MM2S/S2MM channel register bank base). */
#define AXI_DMA_MM2S_DMACR_OFFSET (XAXIDMA_TX_OFFSET + XAXIDMA_CR_OFFSET)
#define AXI_DMA_MM2S_DMASR_OFFSET (XAXIDMA_TX_OFFSET + XAXIDMA_SR_OFFSET)
#define AXI_DMA_MM2S_SA_OFFSET (XAXIDMA_TX_OFFSET + XAXIDMA_SRCADDR_OFFSET)
#define AXI_DMA_MM2S_LENGTH_OFFSET (XAXIDMA_TX_OFFSET + XAXIDMA_BUFFLEN_OFFSET)
#define AXI_DMA_S2MM_DMACR_OFFSET (XAXIDMA_RX_OFFSET + XAXIDMA_CR_OFFSET)
#define AXI_DMA_S2MM_DMASR_OFFSET (XAXIDMA_RX_OFFSET + XAXIDMA_SR_OFFSET)
#define AXI_DMA_S2MM_DA_OFFSET (XAXIDMA_RX_OFFSET + XAXIDMA_DESTADDR_OFFSET)
#define AXI_DMA_S2MM_LENGTH_OFFSET (XAXIDMA_RX_OFFSET + XAXIDMA_BUFFLEN_OFFSET)

#define AXI_DMA_CR_RUNSTOP_MASK XAXIDMA_CR_RUNSTOP_MASK
#define AXI_DMA_CR_RESET_MASK XAXIDMA_CR_RESET_MASK
#define AXI_DMA_SR_HALTED_MASK XAXIDMA_HALTED_MASK
#define AXI_DMA_SR_IDLE_MASK XAXIDMA_IDLE_MASK
#define AXI_DMA_SR_IOC_IRQ_MASK XAXIDMA_IRQ_IOC_MASK
#define AXI_DMA_SR_ALL_IRQ_MASK XAXIDMA_IRQ_ALL_MASK
#define AXI_DMA_SR_ERR_ALL_MASK XAXIDMA_ERR_ALL_MASK
/* CR-side "enable this interrupt type's output pin" bit shares the same bit position as the
 * SR-side status flag above -- standard AXI DMA convention, not a separate generated macro. */
#define AXI_DMA_CR_IOC_IRQ_EN_MASK XAXIDMA_IRQ_IOC_MASK

/* axi_bram_ctrl_0 has no xparameters.h entry: it's mapped only into axi_dma_0's own Data_MM2S/
 * Data_S2MM address spaces, not into microblaze_0/Data (see fpga/bd/fci_bd.tcl's
 * assign_bd_address calls for axi_dma_0), so there's no generated macro to source this from --
 * keep this in sync with that offset (0xC0000000) if it ever changes. */
#define FCI_RESULT_BRAM_BASEADDR 0xC0000000

/* ---------------------------------------------------------------------------------------------
 * axi_iic_0 -- AD8330 VGA gain DAC (address/part TBC, see docs/fpga/DPP4SiPMCMOD_AFE.pdf)
 * ------------------------------------------------------------------------------------------- */
#define AXI_IIC_BASEADDR XPAR_IIC_0_BASEADDR
#define AXI_IIC_DEVICE_ID XPAR_IIC_0_DEVICE_ID

/* ---------------------------------------------------------------------------------------------
 * axi_uartlite_0
 * ------------------------------------------------------------------------------------------- */
#define AXI_UARTLITE_BASEADDR XPAR_UARTLITE_0_BASEADDR
#define AXI_UARTLITE_DEVICE_ID XPAR_UARTLITE_0_DEVICE_ID

/* ---------------------------------------------------------------------------------------------
 * microblaze_0_axi_intc -- xlconcat interrupt aggregation order: In0=dma s2mm, In1=uartlite,
 * In2=fci_core (see fpga/bd/fci_bd.tcl); axi_iic_0/iic2intc_irpt intentionally left unconnected
 * (poll-only I2C).
 * ------------------------------------------------------------------------------------------- */
#define AXI_INTC_BASEADDR XPAR_INTC_0_BASEADDR
#define AXI_INTC_DEVICE_ID XPAR_INTC_0_DEVICE_ID

#define INTC_DMA_S2MM_VEC_ID XPAR_INTC_0_AXIDMA_0_VEC_ID
#define INTC_UARTLITE_VEC_ID XPAR_INTC_0_UARTLITE_0_VEC_ID
#define INTC_FCI_CORE_VEC_ID XPAR_INTC_0_FCI_CORE_0_VEC_ID

/* AXI-mapped (non-DCR) register offsets -- xintc_l.h defines two sets gated on
 * XPAR_XINTC_USE_DCR/_BRIDGE; this design uses neither, so these are the applicable ones. */
#define AXI_INTC_ISR_OFFSET XIN_ISR_OFFSET
#define AXI_INTC_IPR_OFFSET XIN_IPR_OFFSET
#define AXI_INTC_IER_OFFSET XIN_IER_OFFSET
#define AXI_INTC_IAR_OFFSET XIN_IAR_OFFSET
#define AXI_INTC_SIE_OFFSET XIN_SIE_OFFSET
#define AXI_INTC_CIE_OFFSET XIN_CIE_OFFSET
#define AXI_INTC_MER_OFFSET XIN_MER_OFFSET

#define AXI_INTC_MER_ME_MASK XIN_INT_MASTER_ENABLE_MASK   /* Master Enable */
#define AXI_INTC_MER_HIE_MASK XIN_INT_HARDWARE_ENABLE_MASK /* Hardware Interrupt Enable, sticky
                                                             * once set (per xintc_l.h) */

#define INTC_DMA_S2MM_BIT (1U << INTC_DMA_S2MM_VEC_ID)

#endif /* SRC_REGISTERS_H_ */
