/*
 * registers.h
 *
 * Peripheral base addresses and register offsets for the FCI acquisition chain
 * (trigger_core -> fci_core -> axi_dma -> axi_bram_ctrl), plus the AXI IIC/UARTLITE/INTC
 * peripherals shared with the MicroBlaze subsystem.
 *
 * Base addresses are pulled from xparameters.h (regenerated by Vitis from the current hardware
 * platform) rather than hardcoded, so a block-design address-map change can't silently desync
 * this header from the actual bitstream. trigger_core is hand-written RTL with no generated
 * driver, so its register map is defined here by hand -- keep in sync with
 * fpga/rtl/trigger_core/src/axi4lite_regs.vhd if that map ever changes.
 */

#ifndef SRC_REGISTERS_H_
#define SRC_REGISTERS_H_

#include "xparameters.h"
#include "xfci_core_hw.h" /* generated by Vitis HLS; authoritative source for fci_core's
                           * s_axi_control register offsets (see fci_core/drivers/fci_core_v1_0) */

/* ---------------------------------------------------------------------------------------------
 * trigger_core (fpga/rtl/trigger_core) -- hand-written AXI4-Lite register map
 * ------------------------------------------------------------------------------------------- */
#define TRIGGER_CORE_BASEADDR XPAR_TRIGGER_CORE_0_BASEADDR

#define TRIGGER_CORE_THRESHOLD_OFFSET 0x00 /* [13:0], offset-binary ADC code */
#define TRIGGER_CORE_POLARITY_OFFSET 0x04  /* [0]: 1 = rising crossing, 0 = falling crossing */
#define TRIGGER_CORE_DELAY_OFFSET 0x08     /* [8:0], hw-clamped to 2..256 */
#define TRIGGER_CORE_DEPTH_OFFSET 0x0C     /* [12:0], hw-clamped to 1..4096 */

#define TRIGGER_CORE_POLARITY_RISING 0x1
#define TRIGGER_CORE_POLARITY_FALLING 0x0

/* ---------------------------------------------------------------------------------------------
 * fci_core (fpga/hls/fci_core) -- Vitis HLS-generated s_axi_control map, offsets taken directly
 * from xfci_core_hw.h rather than retyped, so a future HLS re-synth/re-export can't desync them.
 * ------------------------------------------------------------------------------------------- */
#define FCI_CORE_BASEADDR XPAR_FCI_CORE_0_S_AXI_CONTROL_BASEADDR

#define FCI_CORE_AP_CTRL_OFFSET XFCI_CORE_CONTROL_ADDR_AP_CTRL /* bit0 ap_start, bit1 ap_done,
                                    * bit2 ap_idle, bit3 ap_ready, bit7 auto_restart, bit9 interrupt */
#define FCI_CORE_GIE_OFFSET XFCI_CORE_CONTROL_ADDR_GIE
#define FCI_CORE_IER_OFFSET XFCI_CORE_CONTROL_ADDR_IER
#define FCI_CORE_ISR_OFFSET XFCI_CORE_CONTROL_ADDR_ISR
#define FCI_CORE_PSA_L_LO_OFFSET XFCI_CORE_CONTROL_ADDR_PSA_L_LO_DATA
#define FCI_CORE_PSA_L_HI_OFFSET XFCI_CORE_CONTROL_ADDR_PSA_L_HI_DATA
#define FCI_CORE_PSA_W_LO_OFFSET XFCI_CORE_CONTROL_ADDR_PSA_W_LO_DATA
#define FCI_CORE_PSA_W_HI_OFFSET XFCI_CORE_CONTROL_ADDR_PSA_W_HI_DATA

#define FCI_CORE_AP_CTRL_START (1U << 0)
#define FCI_CORE_AP_CTRL_DONE (1U << 1)
#define FCI_CORE_AP_CTRL_IDLE (1U << 2)
#define FCI_CORE_AP_CTRL_READY (1U << 3)
#define FCI_CORE_AP_CTRL_AUTO_RESTART (1U << 7)
#define FCI_CORE_AP_CTRL_INTERRUPT (1U << 9)

/* ---------------------------------------------------------------------------------------------
 * axi_dma_0 (Simple DMA, no Scatter-Gather) -- S2MM path carries {PSA_l, PSA_w} per event into
 * axi_bram_ctrl_0; MM2S path reads it back to the MicroBlaze over S0_AXIS for fast readback.
 * ------------------------------------------------------------------------------------------- */
#define AXI_DMA_BASEADDR XPAR_AXI_DMA_0_BASEADDR
#define AXI_DMA_DEVICE_ID XPAR_AXI_DMA_0_DEVICE_ID

#define FCI_RESULT_BRAM_BASEADDR XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR

/* ---------------------------------------------------------------------------------------------
 * axi_iic_0 -- AD8330 VGA gain DAC (address/part TBC, see docs/fpga/DPP4SiPMCMOD_AFE.pdf)
 * ------------------------------------------------------------------------------------------- */
#define AXI_IIC_BASEADDR XPAR_IIC_0_BASEADDR
#define AXI_IIC_DEVICE_ID XPAR_IIC_0_DEVICE_ID

/* ---------------------------------------------------------------------------------------------
 * axi_uartlite_0
 * ------------------------------------------------------------------------------------------- */
#define AXI_UARTLITE_BASEADDR XPAR_UARTLITE_0_BASEADDR
#define AXI_UARTLITE_DEVICE_ID XPAR_UARTLITE_0_DEVICE_ID

/* ---------------------------------------------------------------------------------------------
 * microblaze_0_axi_intc -- xlconcat interrupt aggregation order: In0=dma s2mm, In1=uartlite,
 * In2=fci_core (see fpga/bd/fci_bd.tcl); axi_iic_0/iic2intc_irpt intentionally left unconnected
 * (poll-only I2C).
 * ------------------------------------------------------------------------------------------- */
#define AXI_INTC_BASEADDR XPAR_INTC_0_BASEADDR
#define AXI_INTC_DEVICE_ID XPAR_INTC_0_DEVICE_ID

#define INTC_DMA_S2MM_VEC_ID XPAR_INTC_0_AXIDMA_0_VEC_ID
#define INTC_UARTLITE_VEC_ID XPAR_INTC_0_UARTLITE_0_VEC_ID
#define INTC_FCI_CORE_VEC_ID XPAR_INTC_0_FCI_CORE_0_VEC_ID

#endif /* SRC_REGISTERS_H_ */
