/*
 * registers.h
 *
 * Peripheral base addresses and register offsets for the FCI acquisition chain
 * (trigger_core -> fci_core -> axi_dma -> axi_bram_ctrl), plus the AXI IIC/UARTLITE/INTC
 * peripherals shared with the MicroBlaze subsystem.
 *
 * Base addresses are pulled from xparameters.h (regenerated by Vitis from the current hardware
 * platform) rather than hardcoded, so a block-design address-map change can't silently desync
 * this header from the actual bitstream. trigger_core is hand-written RTL with no generated
 * driver, so its register map is defined here by hand -- keep in sync with
 * fpga/rtl/trigger_core/src/axi4lite_regs.vhd if that map ever changes.
 */

#ifndef SRC_REGISTERS_H_
#define SRC_REGISTERS_H_

#include "xparameters.h"
#include "xaxidma_hw.h"    /* generated by Vitis; authoritative source for axi_dma's direct-
                            * register-mode (Simple DMA) offsets and status/control bit masks */
/* xfci_core_hw.h is deliberately NOT included any more: fci_core is hand-written RTL now, not an
 * HLS export, so there is no generated driver header to defer to and its offsets are stated
 * directly below (against fci_axi4lite_regs.vhd) like every other hand-written core here. */
#include "xintc_l.h"      /* generated by Vitis; authoritative source for axi_intc's register map */

/* ---------------------------------------------------------------------------------------------
 * trigger_core (fpga/rtl/trigger_core) -- hand-written AXI4-Lite register map
 * ------------------------------------------------------------------------------------------- */
#define TRIGGER_CORE_BASEADDR XPAR_TRIGGER_CORE_0_BASEADDR

#define TRIGGER_CORE_THRESHOLD_OFFSET 0x00 /* [13:0], offset-binary ADC code */
#define TRIGGER_CORE_POLARITY_OFFSET 0x04  /* [0]: 1 = rising crossing, 0 = falling crossing */
#define TRIGGER_CORE_DELAY_OFFSET 0x08     /* [8:0], hw-clamped to 2..256 */
#define TRIGGER_CORE_DEPTH_OFFSET 0x0C     /* [12:0], hw-clamped to 1..4096 */

#define TRIGGER_CORE_POLARITY_RISING 0x1
#define TRIGGER_CORE_POLARITY_FALLING 0x0

/* ---------------------------------------------------------------------------------------------
 * blr_core (fpga/rtl/blr_core) -- hand-written AXI4-Lite register map, keep in sync with
 * blr_axi4lite_regs.vhd.
 *
 * blr_core sits between the ADC pins and trigger_core and restores the baseline to ZERO, emitting
 * SIGNED samples. Thresholds, integration references and trace statistics are all signed levels
 * about zero -- there is no mid-scale constant anywhere in the chain.
 * ------------------------------------------------------------------------------------------- */
#define BLR_CORE_BASEADDR XPAR_BLR_CORE_0_BASEADDR

#define BLR_SHIFT_OFFSET 0x00    /* [3:0]  EMA shift k; time constant = 2^k samples */
#define BLR_GATE_THR_OFFSET 0x04 /* [13:0] freeze the estimator at/above this deviation */
#define BLR_CTRL_OFFSET 0x08     /* [0] bypass, [1] hold */
#define BLR_STATUS_OFFSET 0x0C   /* RO: [13:0] live baseline (SIGNED, sign-extend on read),
                                  *     [31] gate open */
#define BLR_HOLDOFF_OFFSET 0x10  /* [11:0] extra closed samples after a pulse falls back in range */

#define BLR_CTRL_BYPASS_MASK (1U << 0)
#define BLR_CTRL_HOLD_MASK (1U << 1)
#define BLR_STATUS_BASELINE_MASK 0x3FFFU
#define BLR_STATUS_GATE_OPEN_MASK (1U << 31)

/* Width of the signed baseline field in BLR_STATUS_OFFSET, for sign extension in blr.c. */
#define BLR_BASELINE_BITS 14

/* ---------------------------------------------------------------------------------------------
 * psd_core (fpga/rtl/psd_core) -- hand-written AXI4-Lite register map, keep in sync with
 * psd_axi4lite_regs.vhd.
 * ------------------------------------------------------------------------------------------- */
#define PSD_CORE_BASEADDR XPAR_PSD_CORE_0_BASEADDR

#define PSD_PRE_TRIGGER_OFFSET 0x00  /* must match trigger_core's delay register */
#define PSD_PRE_GATE_OFFSET 0x04
#define PSD_SHORT_GATE_OFFSET 0x08
#define PSD_LONG_GATE_OFFSET 0x0C
#define PSD_BASELINE_REF_OFFSET 0x10 /* SIGNED residual-pedestal trim; 0 when fed by blr_core */
#define PSD_CTRL_OFFSET 0x14         /* W, self-clearing: [0] pop, [1] clear */
#define PSD_STATUS_OFFSET 0x18       /* RO */
#define PSD_ENERGY_SHORT_OFFSET 0x1C /* RO, signed */
#define PSD_ENERGY_LONG_OFFSET 0x20  /* RO, signed */
#define PSD_TS_LO_OFFSET 0x24        /* RO */
#define PSD_TS_HI_OFFSET 0x28        /* RO */
#define PSD_EVENT_COUNT_OFFSET 0x2C  /* RO */
#define PSD_WATERMARK_OFFSET 0x30    /* irq_o asserts at this FIFO level; 0 disables */

#define PSD_CTRL_POP_MASK (1U << 0)
#define PSD_CTRL_CLEAR_MASK (1U << 1)
#define PSD_STATUS_EMPTY_MASK (1U << 0)
#define PSD_STATUS_FULL_MASK (1U << 1)
#define PSD_STATUS_OVERFLOW_MASK (1U << 2)
#define PSD_STATUS_LEVEL_SHIFT 8
#define PSD_STATUS_LEVEL_MASK 0x3FU

/* ---------------------------------------------------------------------------------------------
 * fci_core (fpga/rtl/fci_core_rtl) -- hand-written VHDL core: 2048-point FFT, two programmable bin
 * windows, and a 32-deep buffered result FIFO, all in ONE AXI4-Lite map. Keep in sync with
 * fci_axi4lite_regs.vhd.
 *
 * This replaced two separate IPs. The Vitis HLS fci_core truncated each FFT bin's magnitude to an
 * ap_ufixed<18,2>; with block-floating-point scaling (whose per-frame exponent is set by the
 * largest bin) that put every bin far from this detector's very low spectral corner below the
 * quantization floor, and measurably destroyed the discrimination signal -- across three live
 * recordings under a DD generator, FCI in the Li-6 capture band sat at cv 11.6-27.3% with no
 * gamma/neutron separation while PSD on the SAME events held cv 0.10%. The RTL core accumulates
 * full width instead; the same pulses recomputed in float give cv 0.82-1.59%, which is the number
 * to expect once this is in silicon. fci_sink was a
 * separate IP only because an HLS core cannot expose a FIFO-backed register window; hand-written
 * RTL can, so it is merged in here and its former base address is gone.
 *
 * The FCI_SINK_* names are kept as-is rather than renamed: fci_sink.c's accessors work unchanged
 * against this map (same semantics, same bit layout), and renaming them would churn every call
 * site for no behavioural gain. Only the base address and two offsets actually moved.
 * ------------------------------------------------------------------------------------------- */
/* Resolved from whatever the block design actually called the cell, because that is not fixed: the
 * merged core was planned as `fci_core_rtl_0` but was instanced as `fci_core_0`, reusing the
 * retired HLS core's name. Both spellings are accepted rather than hardcoding one.
 *
 * The name alone cannot say WHICH core is present, though -- `fci_core_0` was also the HLS core's
 * cell name, and that one has no result FIFO, so firmware must not take the fci_sink path against
 * it. `irq_o` disambiguates: it is a port only the RTL core has (the HLS core's interrupt came from
 * ap_done, exported under a different name), so its XPAR mask is a hardware-derived signature of
 * the merged core rather than a hand-maintained switch. FCI_CORE_HAS_RESULT_FIFO carries that
 * answer to bringup.c, which selects its result path from it. */
#if defined(XPAR_FCI_CORE_RTL_0_BASEADDR)
#define FCI_CORE_BASEADDR XPAR_FCI_CORE_RTL_0_BASEADDR
#define FCI_CORE_HAS_RESULT_FIFO 1
#elif defined(XPAR_FCI_CORE_0_IRQ_O_MASK)
#define FCI_CORE_BASEADDR XPAR_FCI_CORE_0_BASEADDR
#define FCI_CORE_HAS_RESULT_FIFO 1
#elif defined(XPAR_FCI_CORE_0_BASEADDR)
#define FCI_CORE_BASEADDR XPAR_FCI_CORE_0_BASEADDR /* legacy HLS core, no result FIFO */
#define FCI_CORE_HAS_RESULT_FIFO 0
#else
#error "No FCI core found in xparameters.h -- regenerate the BSP against the current block design"
#endif

/* THE single answer to "does this bitstream deliver FCI results through a FIFO-backed register
 * window?", for every module that needs to know: bringup.c picks its result path from it,
 * acquisition.c compiles to nothing without it, cli.c reports the result commands as unavailable.
 *
 * It lives here, in one place, because it previously did not: three files each derived it
 * independently from `#ifdef XPAR_FCI_SINK_0_BASEADDR`, and when fci_sink was merged into the FCI
 * core that symbol disappeared from all three at once. Two of them failed loudly, but acquisition.c
 * merely compiled to an empty translation unit and the build got all the way to a link error about
 * an unrelated-looking symbol. One definition cannot drift from itself. */
#if defined(XPAR_FCI_SINK_0_BASEADDR) || FCI_CORE_HAS_RESULT_FIFO
#define FCI_RESULT_VIA_FCI_SINK 1
#else
#define FCI_RESULT_VIA_FCI_SINK 0
#endif

/* Bin-window bounds. Bin indices now run 0..2047 (Nyquist at 1024) rather than 0..1023. */
#define FCI_CORE_PSA_L_LO_OFFSET 0x00
#define FCI_CORE_PSA_L_HI_OFFSET 0x04
#define FCI_CORE_PSA_W_LO_OFFSET 0x08
#define FCI_CORE_PSA_W_HI_OFFSET 0x0C

/* Buffered result window. Same field semantics as the old fci_sink map, but psa_l/psa_w moved from
 * 0x08/0x0C (now occupied by the window bounds above) to 0x18/0x1C, and everything after shifted
 * with them. */
#define FCI_SINK_BASEADDR FCI_CORE_BASEADDR
#define FCI_SINK_CTRL_OFFSET 0x10        /* W, self-clearing: [0] pop, [1] clear */
#define FCI_SINK_STATUS_OFFSET 0x14      /* RO */
#define FCI_SINK_PSA_L_OFFSET 0x18       /* RO, raw magnitude sum (see below) */
#define FCI_SINK_PSA_W_OFFSET 0x1C       /* RO, raw magnitude sum (see below) */
#define FCI_SINK_TS_LO_OFFSET 0x20       /* RO */
#define FCI_SINK_TS_HI_OFFSET 0x24       /* RO */
#define FCI_SINK_EVENT_COUNT_OFFSET 0x28 /* RO */
#define FCI_SINK_WATERMARK_OFFSET 0x2C

/* psa_l/psa_w are raw 32-bit unsigned sums of 17-bit |Re|+|Im| magnitudes, NOT the HLS core's
 * Q12.16 fixed point. The scale is arbitrary but identical for both windows, and firmware only
 * ever forms their ratio (fci_sink.c's FciSink_RatioScaled), so nothing downstream cares -- but a
 * reader comparing these numbers against old logs will find them much larger. */

#define FCI_SINK_CTRL_POP_MASK (1U << 0)
#define FCI_SINK_CTRL_CLEAR_MASK (1U << 1)
#define FCI_SINK_STATUS_EMPTY_MASK (1U << 0)
#define FCI_SINK_STATUS_FULL_MASK (1U << 1)
#define FCI_SINK_STATUS_OVERFLOW_MASK (1U << 2)
/* Bit 3 (framing error) has no equivalent in the merged core: it existed because fci_sink had to
 * reassemble a two-beat result stream and could observe a malformed pair. The accumulator hands
 * results over directly now, so there is no framing to get wrong. Reads back 0 always; kept so
 * FciSink_FramingError() still compiles and reports "no error". */
#define FCI_SINK_STATUS_FRAMING_ERR_MASK (1U << 3)
#define FCI_SINK_STATUS_LEVEL_SHIFT 8
#define FCI_SINK_STATUS_LEVEL_MASK 0x3FU

/* ---------------------------------------------------------------------------------------------
 * axi_dma_0 (Simple DMA, no Scatter-Gather) -- S2MM path carries {PSA_l, PSA_w} per event into
 * axi_bram_ctrl_0; MM2S path reads it back to the MicroBlaze over S0_AXIS for fast readback.
 *
 * axi_dma_1 is a second, identically-configured Simple DMA instance added for raw-trace capture:
 * S2MM carries trigger_core's raw ADC samples (tapped via axis_broadcaster_0, 16-bit stream) into
 * the same axi_bram_ctrl_0 at a different offset (see RAW_TRACE_BRAM_BASEADDR below); MM2S reads
 * back out over microblaze_0/S1_AXIS (note: stream index 1, not 0, in the getfslx() call). Both
 * instances share the exact same channel-relative register layout, so dma_s2mm.h's functions take
 * a dma_baseaddr parameter (AXI_DMA_BASEADDR or AXI_DMA_1_BASEADDR) rather than being duplicated.
 * ------------------------------------------------------------------------------------------- */
/* Guarded because axi_dma_0 is the block design's decision, same as XPAR_FCI_SINK_0_BASEADDR
 * below: once fci_sink replaces it (issue #12 BD integration), a BD without axi_dma_0 must not
 * fail to build registers.h itself over a macro nothing still uses. */
#ifdef XPAR_AXI_DMA_0_BASEADDR
#define AXI_DMA_BASEADDR XPAR_AXI_DMA_0_BASEADDR
#define AXI_DMA_DEVICE_ID XPAR_AXI_DMA_0_DEVICE_ID
#endif

#define AXI_DMA_1_BASEADDR XPAR_AXI_DMA_1_BASEADDR
#define AXI_DMA_1_DEVICE_ID XPAR_AXI_DMA_1_DEVICE_ID

/* c_include_sg=0 (Simple DMA): direct-register mode only, channel-relative offsets from
 * xaxidma_hw.h (XAXIDMA_TX_OFFSET/XAXIDMA_RX_OFFSET = MM2S/S2MM channel register bank base).
 * Channel-relative, so the same offsets apply to axi_dma_1 too -- only the base address differs.
 * Unguarded: axi_dma_1 (raw-trace capture) always exists regardless of axi_dma_0/fci_sink, and
 * these offsets come from xaxidma_hw.h, not from a per-instance XPAR symbol. */
#define AXI_DMA_MM2S_DMACR_OFFSET (XAXIDMA_TX_OFFSET + XAXIDMA_CR_OFFSET)
#define AXI_DMA_MM2S_DMASR_OFFSET (XAXIDMA_TX_OFFSET + XAXIDMA_SR_OFFSET)
#define AXI_DMA_MM2S_SA_OFFSET (XAXIDMA_TX_OFFSET + XAXIDMA_SRCADDR_OFFSET)
#define AXI_DMA_MM2S_LENGTH_OFFSET (XAXIDMA_TX_OFFSET + XAXIDMA_BUFFLEN_OFFSET)
#define AXI_DMA_S2MM_DMACR_OFFSET (XAXIDMA_RX_OFFSET + XAXIDMA_CR_OFFSET)
#define AXI_DMA_S2MM_DMASR_OFFSET (XAXIDMA_RX_OFFSET + XAXIDMA_SR_OFFSET)
#define AXI_DMA_S2MM_DA_OFFSET (XAXIDMA_RX_OFFSET + XAXIDMA_DESTADDR_OFFSET)
#define AXI_DMA_S2MM_LENGTH_OFFSET (XAXIDMA_RX_OFFSET + XAXIDMA_BUFFLEN_OFFSET)

#define AXI_DMA_CR_RUNSTOP_MASK XAXIDMA_CR_RUNSTOP_MASK
#define AXI_DMA_CR_RESET_MASK XAXIDMA_CR_RESET_MASK
#define AXI_DMA_SR_HALTED_MASK XAXIDMA_HALTED_MASK
#define AXI_DMA_SR_IDLE_MASK XAXIDMA_IDLE_MASK
#define AXI_DMA_SR_IOC_IRQ_MASK XAXIDMA_IRQ_IOC_MASK
#define AXI_DMA_SR_ALL_IRQ_MASK XAXIDMA_IRQ_ALL_MASK
#define AXI_DMA_SR_ERR_ALL_MASK XAXIDMA_ERR_ALL_MASK
/* CR-side "enable this interrupt type's output pin" bit shares the same bit position as the
 * SR-side status flag above -- standard AXI DMA convention, not a separate generated macro. */
#define AXI_DMA_CR_IOC_IRQ_EN_MASK XAXIDMA_IRQ_IOC_MASK

/* axi_bram_ctrl_0/axi_bram_ctrl_1 have no xparameters.h entries: each is mapped only into the two
 * DMA engines' own Data_MM2S/Data_S2MM address spaces, not into microblaze_0/Data (see
 * fpga/bd/fci_bd.tcl's assign_bd_address calls), so there's no generated macro to source these
 * from -- keep in sync with those offsets if they ever change.
 *
 * Two separate, same-width (32-bit) BRAM blocks rather than one shared/widened block: PSA_l/PSA_w
 * (8KB, plenty of headroom for the 8-byte result plus double-buffer slots) and raw-trace capture
 * (a second, independent 8KB block, dedicated to axi_dma_1). Deliberately not sharing one wider
 * block across both DMA engines -- that would need axi_smc doing live width conversion between
 * the 32-bit DMA masters and a wider shared memory, which is an unnecessary correctness risk for
 * no real resource savings (two matched 8KB blocks costs about the same BRAM as one wide 16KB
 * one). */
#define FCI_RESULT_BRAM_BASEADDR 0xC0000000

/* axi_dma_1's S2MM stream is 16-bit (matching trigger_core's raw samples) but its memory-side bus
 * is 32-bit (C_M_AXI_S2MM_DATA_WIDTH, confirmed in the exported .hwh), so it packs two 16-bit
 * samples per 32-bit memory word -- transfer length is still depth*2 bytes, but MM2S readback
 * only needs depth/2 getfslx() calls, each unpacked into two samples (see main.c). */
#define RAW_TRACE_BRAM_BASEADDR 0xC2000000

/* ---------------------------------------------------------------------------------------------
 * axi_timer_0 -- added for future use (calibrated wall-clock timing, per-event timestamps for
 * list mode); not yet consumed by any firmware in this project.
 * ------------------------------------------------------------------------------------------- */
#define AXI_TIMER_0_BASEADDR XPAR_AXI_TIMER_0_BASEADDR
#define AXI_TIMER_0_DEVICE_ID XPAR_AXI_TIMER_0_DEVICE_ID

/* ---------------------------------------------------------------------------------------------
 * axi_iic_0 -- AD8330 VGA gain DAC (address/part TBC, see docs/fpga/DPP4SiPMCMOD_AFE.pdf)
 * ------------------------------------------------------------------------------------------- */
#define AXI_IIC_BASEADDR XPAR_IIC_0_BASEADDR
#define AXI_IIC_DEVICE_ID XPAR_IIC_0_DEVICE_ID

/* ---------------------------------------------------------------------------------------------
 * axi_uartlite_0
 * ------------------------------------------------------------------------------------------- */
#define AXI_UARTLITE_BASEADDR XPAR_UARTLITE_0_BASEADDR
#define AXI_UARTLITE_DEVICE_ID XPAR_UARTLITE_0_DEVICE_ID

/* ---------------------------------------------------------------------------------------------
 * microblaze_0_axi_intc -- xlconcat interrupt aggregation order. As currently wired in
 * fpga/bd/fci_bd.tcl: In0=uartlite, In1=axi_timer_0, In2=fci_core, In3=psd_core, In4=axi_dma_0
 * s2mm, In5=axi_dma_1 s2mm. This order has changed more than once; nothing in firmware depends on
 * it because every vector ID below is read from the generated xparameters.h. Vec IDs below are read from the generated
 * xparameters.h rather than hardcoded, so this reordering doesn't require any code change here --
 * only a BSP regeneration in Vitis. axi_iic_0/iic2intc_irpt intentionally left unconnected
 * (poll-only I2C).
 * ------------------------------------------------------------------------------------------- */
#define AXI_INTC_BASEADDR XPAR_INTC_0_BASEADDR
#define AXI_INTC_DEVICE_ID XPAR_INTC_0_DEVICE_ID

#ifdef XPAR_AXI_DMA_0_BASEADDR
#define INTC_DMA_S2MM_VEC_ID XPAR_INTC_0_AXIDMA_0_VEC_ID
#endif

/* Two BSP naming schemes, tried newest first.
 *
 * The modern one (XPAR_<intc>_<source-port>_INTR) names the source cell and port literally, so it
 * is unambiguous. The legacy canonical one (XPAR_INTC_0_AXIDMA_<N>_VEC_ID) numbered by POSITION
 * among AXI-DMA-type sources rather than by instance name, which was a real hazard here: with both
 * axi_dma_0 and axi_dma_1 present they landed on 0 and 1 matching the cell names, but deleting
 * axi_dma_0 renumbered axi_dma_1's OWN macro down into the _0 slot while XPAR_AXI_DMA_1_BASEADDR
 * stayed put. The legacy branches below still carry that disambiguation for older BSP exports.
 *
 * axi_dma_0 is now gone for real (the merged core delivers results through its own register window
 * instead of the FSL/BRAM path), and this BSP exports only the modern names -- hence the first
 * branch. Note XPAR_AXIDMA_0_BASEADDR does exist here but is a canonical ALIAS for axi_dma_1, not
 * a second DMA; do not treat it as evidence axi_dma_0 is present. */
/* ---------------------------------------------------------------------------------------------
 * OVERRIDE: the BSP is WRONG about this vector on the current block design, so it is not used.
 *
 * fci_bd.tcl connects axi_dma_1/s2mm_introut to microblaze_0_xlconcat/In5, and In4 is left
 * UNCONNECTED (a hole left behind when fci_core_0's HLS interrupt and fci_sink_0 were removed).
 * An unconnected xlconcat input ties to 0, so INTC bit 4 can never assert. The BSP nevertheless
 * generates XPAR_..._AXI_DMA_1_S2MM_INTROUT_INTR = 4 and _MASK = 0x10, apparently numbering
 * connected sources sequentially and ignoring the gap, so BOTH generated macros are off by one.
 *
 * Measured on hardware 2026-08-31, and the arithmetic is unambiguous: with a raw trace completed
 * (S2MM_DMASR = 0x1002, Idle + IOC_Irq) the controller reported ISR = 0x2C -- bits 2, 3 and 5, so
 * the DMA line is asserting on bit 5 exactly where the BD wired it -- while firmware had enabled
 * IER = 0x10 (bit 4) from the BSP. IPR = ISR & IER = 0x2C & 0x10 = 0, matching the reported
 * IPR = 0. The completion interrupt was therefore never delivered, the ISR never re-armed S2MM,
 * and because axis_broadcaster_0 is lockstep that stalled psd_core and fci_core too and left
 * trigger_core permanently un-armed: zero triggers at ANY threshold or polarity.
 *
 * The proper fix is in the block design -- move s2mm_introut to In4 so there is no gap and the
 * BSP's own numbering becomes correct -- at which point this override should be deleted and the
 * generated macro used again. It is kept as an explicit constant, not a "+1", because the right
 * value is a property of the BD's wiring, not an offset from a broken one.
 * ------------------------------------------------------------------------------------------- */
#define INTC_DMA_1_S2MM_VEC_ID_BD_OVERRIDE 5

#if defined(INTC_DMA_1_S2MM_VEC_ID_BD_OVERRIDE)
#define INTC_DMA_1_S2MM_VEC_ID INTC_DMA_1_S2MM_VEC_ID_BD_OVERRIDE
#elif defined(XPAR_MICROBLAZE_0_AXI_INTC_AXI_DMA_1_S2MM_INTROUT_INTR)
#define INTC_DMA_1_S2MM_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_DMA_1_S2MM_INTROUT_INTR
#elif defined(XPAR_INTC_0_AXIDMA_1_VEC_ID)
#define INTC_DMA_1_S2MM_VEC_ID XPAR_INTC_0_AXIDMA_1_VEC_ID
#elif defined(XPAR_INTC_0_AXIDMA_0_VEC_ID) && !defined(XPAR_AXI_DMA_0_BASEADDR)
#define INTC_DMA_1_S2MM_VEC_ID XPAR_INTC_0_AXIDMA_0_VEC_ID
#else
#error "axi_dma_1's interrupt vector not found -- regenerate the BSP against the current BD"
#endif

#if defined(XPAR_MICROBLAZE_0_AXI_INTC_AXI_UARTLITE_0_INTERRUPT_INTR)
#define INTC_UARTLITE_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_UARTLITE_0_INTERRUPT_INTR
#elif defined(XPAR_INTC_0_UARTLITE_0_VEC_ID)
#define INTC_UARTLITE_VEC_ID XPAR_INTC_0_UARTLITE_0_VEC_ID
#endif

/* The merged RTL core's watermark interrupt. Currently defined for documentation of the vector map
 * only -- firmware polls fci_sink's FIFO rather than taking this interrupt. */
#if defined(XPAR_MICROBLAZE_0_AXI_INTC_FCI_CORE_0_IRQ_O_INTR)
#define INTC_FCI_CORE_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_FCI_CORE_0_IRQ_O_INTR
#elif defined(XPAR_INTC_0_FCI_CORE_0_VEC_ID)
#define INTC_FCI_CORE_VEC_ID XPAR_INTC_0_FCI_CORE_0_VEC_ID
#endif

/* AXI-mapped (non-DCR) register offsets -- xintc_l.h defines two sets gated on
 * XPAR_XINTC_USE_DCR/_BRIDGE; this design uses neither, so these are the applicable ones. */
#define AXI_INTC_ISR_OFFSET XIN_ISR_OFFSET
#define AXI_INTC_IPR_OFFSET XIN_IPR_OFFSET
#define AXI_INTC_IER_OFFSET XIN_IER_OFFSET
#define AXI_INTC_IAR_OFFSET XIN_IAR_OFFSET
#define AXI_INTC_SIE_OFFSET XIN_SIE_OFFSET
#define AXI_INTC_CIE_OFFSET XIN_CIE_OFFSET
#define AXI_INTC_MER_OFFSET XIN_MER_OFFSET

#define AXI_INTC_MER_ME_MASK XIN_INT_MASTER_ENABLE_MASK   /* Master Enable */
#define AXI_INTC_MER_HIE_MASK XIN_INT_HARDWARE_ENABLE_MASK /* Hardware Interrupt Enable, sticky
                                                             * once set (per xintc_l.h) */

#ifdef XPAR_AXI_DMA_0_BASEADDR
#define INTC_DMA_S2MM_BIT (1U << INTC_DMA_S2MM_VEC_ID)
#endif
#define INTC_DMA_1_S2MM_BIT (1U << INTC_DMA_1_S2MM_VEC_ID)

#endif /* SRC_REGISTERS_H_ */
